import { makeCopy } from '@/lib/copy';

const sq = {
  eyebrow: 'Faturat dhe arka',
  title: 'Çdo faturë, e fiskalizuar.',
  subtitle: 'Nga fatura e dhomës te porosia e barit: numër rendor, NIVF, NSLF dhe kod QR. Arka mbyllet me numërim dhe diferencat bien në sy.',
  tabs: { invoices: 'Faturat', cash: 'Arka' },
  filters: { all: 'Të gjitha', fiscalized: 'Fiskalizuara', issued: 'Të lëshuara', failed: 'Dështuara', cancelled: 'Anuluara' },
  status: { draft: 'Draft', issued: 'E lëshuar', fiscalized: 'Fiskalizuar', cancelled: 'Anuluar', failed: 'Dështoi' } as Record<string, string>,
  search: 'Kërko numër, blerës, NIVF…',
  newInvoice: 'Faturë e re',
  empty: 'Asnjë faturë këtu.',
  cols: { number: 'Nr.', date: 'Data', buyer: 'Blerësi', total: 'Totali', status: 'Statusi' },
  anon: 'Klient pa emër',
  source: 'Burimi',
  fromFolio: 'Fatura e dhomës (largime)',
  fromPos: 'Shitje bar/restorant (cash, kartë)',
  pick: 'Zgjidh…',
  buyerName: 'Emri i blerësit',
  buyerNipt: 'NIPT (opsionale)',
  buyerAddress: 'Adresa (opsionale)',
  method: 'Mënyra e pagesës',
  methods: { cash: 'Cash', card: 'Kartë', bank_transfer: 'Bankë', online: 'Online', room_charge: 'Në dhomë' } as Record<string, string>,
  fiscalizeNow: 'Fiskalizo menjëherë',
  issue: 'Lësho faturën',
  nothingToInvoice: 'Nuk ka asgjë për t’u faturuar.',
  detail: { seller: 'Shitësi', buyer: 'Blerësi', lines: 'Artikujt', subtotal: 'Pa TVSH', vat: 'TVSH', total: 'Totali', nivf: 'NIVF', nslf: 'NSLF', provider: 'Ofruesi', print: 'Printo / PDF', fiscalize: 'Fiskalizo', cancel: 'Anulo faturën', reason: 'Arsyeja', confirmCancel: 'Anulo', mockNote: 'Kodet janë demo dhe nuk kanë vlerë ligjore.', close: 'Mbyll' },
  cash: {
    title: 'Arka ime',
    noShift: 'Nuk ke turn të hapur.',
    opening: 'Cash fillestar',
    open: 'Hap turnin',
    running: 'Pritet në arkë',
    counted: 'Cash i numëruar',
    close: 'Mbyll turnin',
    notes: 'Shënime',
    history: 'Turnet e fundit',
    diff: 'Diferenca',
    since: 'Hapur',
    closed: (d: number) => (Math.abs(d) < 1 ? 'Turni u mbyll. Arka përputhet.' : `Turni u mbyll. Diferenca: ${d > 0 ? '+' : ''}${d.toFixed(2)}`),
    openShift: 'Hapur',
  },
  errors: {
    invalid: 'Kontrollo fushat.', forbidden: 'Nuk ke leje.', module: 'Moduli është i çaktivizuar.', notFound: 'Nuk u gjet.', emptyInvoice: 'Nuk ka artikuj për faturë.',
    alreadyInvoiced: 'Ky burim ka tashmë një faturë.', badStatus: 'Statusi nuk e lejon.', fiscalFailed: 'Fiskalizimi dështoi. Provo përsëri.', shiftOpen: 'Ke tashmë një turn të hapur.', unknown: 'Diçka shkoi keq.',
  } as Record<string, string>,
};

const en: typeof sq = {
  eyebrow: 'Invoices and cash',
  title: 'Every invoice, fiscalized.',
  subtitle: 'From the room folio to the bar order: sequential number, NIVF, NSLF and QR code. The register closes with a count and differences stand out.',
  tabs: { invoices: 'Invoices', cash: 'Cash register' },
  filters: { all: 'All', fiscalized: 'Fiscalized', issued: 'Issued', failed: 'Failed', cancelled: 'Cancelled' },
  status: { draft: 'Draft', issued: 'Issued', fiscalized: 'Fiscalized', cancelled: 'Cancelled', failed: 'Failed' },
  search: 'Search number, buyer, NIVF…',
  newInvoice: 'New invoice',
  empty: 'No invoices here.',
  cols: { number: 'No.', date: 'Date', buyer: 'Buyer', total: 'Total', status: 'Status' },
  anon: 'Walk-in customer',
  source: 'Source',
  fromFolio: 'Room folio (departures)',
  fromPos: 'Bar/restaurant sale (cash, card)',
  pick: 'Pick…',
  buyerName: 'Buyer name',
  buyerNipt: 'Tax ID / NIPT (optional)',
  buyerAddress: 'Address (optional)',
  method: 'Payment method',
  methods: { cash: 'Cash', card: 'Card', bank_transfer: 'Bank', online: 'Online', room_charge: 'Room charge' },
  fiscalizeNow: 'Fiscalize immediately',
  issue: 'Issue invoice',
  nothingToInvoice: 'Nothing left to invoice.',
  detail: { seller: 'Seller', buyer: 'Buyer', lines: 'Items', subtotal: 'Net', vat: 'VAT', total: 'Total', nivf: 'NIVF', nslf: 'NSLF', provider: 'Provider', print: 'Print / PDF', fiscalize: 'Fiscalize', cancel: 'Cancel invoice', reason: 'Reason', confirmCancel: 'Cancel', mockNote: 'Codes are demo values with no legal effect.', close: 'Close' },
  cash: {
    title: 'My register',
    noShift: 'You have no open shift.',
    opening: 'Opening cash',
    open: 'Open shift',
    running: 'Expected in drawer',
    counted: 'Counted cash',
    close: 'Close shift',
    notes: 'Notes',
    history: 'Recent shifts',
    diff: 'Difference',
    since: 'Opened',
    closed: (d) => (Math.abs(d) < 1 ? 'Shift closed. The drawer matches.' : `Shift closed. Difference: ${d > 0 ? '+' : ''}${d.toFixed(2)}`),
    openShift: 'Open',
  },
  errors: {
    invalid: 'Check the fields.', forbidden: 'Not allowed.', module: 'Module disabled.', notFound: 'Not found.', emptyInvoice: 'No items to invoice.',
    alreadyInvoiced: 'This source already has an invoice.', badStatus: 'Status does not allow this.', fiscalFailed: 'Fiscalization failed. Try again.', shiftOpen: 'You already have an open shift.', unknown: 'Something went wrong.',
  },
};

export const pickInvoicesCopy = makeCopy(sq, en);
