import { makeCopy } from '@/lib/copy';

const sq = {
  eyebrow: 'Raportet',
  title: 'Numrat, të shpjeguar thjesht.',
  subtitle: 'Të ardhurat, pushtimi, kanalet dhe kush çfarë ka bërë. Eksporto në Excel ose PDF kur të duhet.',
  presets: { '7': '7 ditë', '30': '30 ditë', month: 'Ky muaj', lastMonth: 'Muaji i kaluar', ytd: 'Viti' },
  from: 'Nga',
  to: 'Deri',
  apply: 'Apliko',
  kpi: { revenue: 'Të ardhura', occupancy: 'Pushtimi', adr: 'Çmimi mesatar / natë', revpar: 'Të ardhura / dhomë', bookings: 'Rezervime të reja', cancellations: 'Anulime' },
  kpiHelp: { occupancy: 'Sa % e netëve të dhomave u shitën.', adr: 'Sa paguan mesatarisht një mysafir për një natë (ADR).', revpar: 'Të ardhurat e dhomave pjesëtuar me të gjitha dhomat (RevPAR).' },
  vsPrev: 'kundrejt periudhës së kaluar',
  revenueByDay: 'Të ardhurat ditë pas dite',
  rooms: 'Dhoma',
  fb: 'Restorant & bar',
  spa: 'Spa',
  channels: 'Rezervimet sipas kanalit',
  channelCols: { source: 'Kanali', bookings: 'Rezervime', nights: 'Net', revenue: 'Të ardhura', commission: 'Komision' },
  outlets: 'Shitjet e restorantit, barit dhe pishinës',
  expenses: 'Shpenzimet sipas departamentit',
  profit: 'Fitimi i periudhës',
  activity: 'Aktiviteti i stafit',
  allStaff: 'Të gjithë',
  time: 'Koha',
  user: 'Përdoruesi',
  action: 'Veprimi',
  system: 'Sistemi',
  export: 'Eksporto',
  exportKinds: { bookings: 'Rezervimet', invoices: 'Faturat', expenses: 'Shpenzimet', payments: 'Pagesat', activity: 'Aktiviteti' },
  pdf: 'PDF / Printo',
  source: { direct: 'Direkt', website: 'Faqja', booking_com: 'Booking.com', airbnb: 'Airbnb', expedia: 'Expedia', agoda: 'Agoda', whatsapp: 'WhatsApp', instagram: 'Instagram', messenger: 'Messenger', phone: 'Telefon', ai_voice: 'Asistenti zanor', walk_in: 'Pa rezervim' } as Record<string, string>,
  empty: 'Asnjë e dhënë për këtë periudhë.',
};

const en: typeof sq = {
  eyebrow: 'Reports',
  title: 'The numbers, simply explained.',
  subtitle: 'Revenue, occupancy, channels and who did what. Export to Excel or PDF whenever you need.',
  presets: { '7': '7 days', '30': '30 days', month: 'This month', lastMonth: 'Last month', ytd: 'Year' },
  from: 'From',
  to: 'To',
  apply: 'Apply',
  kpi: { revenue: 'Revenue', occupancy: 'Occupancy', adr: 'Average price / night', revpar: 'Revenue / room', bookings: 'New bookings', cancellations: 'Cancellations' },
  kpiHelp: { occupancy: 'The % of room-nights that were sold.', adr: 'What a guest pays on average for one night (ADR).', revpar: 'Room revenue divided by all rooms (RevPAR).' },
  vsPrev: 'vs previous period',
  revenueByDay: 'Revenue day by day',
  rooms: 'Rooms',
  fb: 'Restaurant & bar',
  spa: 'Spa',
  channels: 'Bookings by channel',
  channelCols: { source: 'Channel', bookings: 'Bookings', nights: 'Nights', revenue: 'Revenue', commission: 'Commission' },
  outlets: 'Restaurant, bar and pool sales',
  expenses: 'Expenses by department',
  profit: 'Profit for the period',
  activity: 'Staff activity',
  allStaff: 'Everyone',
  time: 'Time',
  user: 'User',
  action: 'Action',
  system: 'System',
  export: 'Export',
  exportKinds: { bookings: 'Bookings', invoices: 'Invoices', expenses: 'Expenses', payments: 'Payments', activity: 'Activity' },
  pdf: 'PDF / Print',
  source: { direct: 'Direct', website: 'Website', booking_com: 'Booking.com', airbnb: 'Airbnb', expedia: 'Expedia', agoda: 'Agoda', whatsapp: 'WhatsApp', instagram: 'Instagram', messenger: 'Messenger', phone: 'Phone', ai_voice: 'AI voice', walk_in: 'Walk-in' },
  empty: 'No data for this period.',
};

export const pickReportsCopy = makeCopy(sq, en);
