import { makeCopy } from '@/lib/copy';

const sq = {
  eyebrow: 'Bar, restorant dhe pishina',
  title: 'Porosia shkon, faturimi vetë.',
  subtitle: 'Merr porosinë, dërgoje në kuzhinë, dhe ngarkoje në dhomën e mysafirit me një klik.',
  today: 'Sot',
  sales: 'Shitje',
  orders: 'porosi',
  tables: 'Tavolinat',
  noTable: 'Pa tavolinë',
  seats: 'vende',
  free: 'e lirë',
  open: 'e hapur',
  order: 'Porosia',
  empty: 'Zgjidh produkte nga menyja.',
  covers: 'Persona',
  discount: 'Zbritje %',
  discountHint: (n: number) => `Mbi ${n}% kërkon menaxher`,
  subtotal: 'Nëntotali',
  total: 'Totali',
  send: 'Dërgo në kuzhinë',
  sent: 'U dërgua.',
  saved: 'U ruajt.',
  pay: 'Paguaj',
  void: 'Anulo porosinë',
  voidReason: 'Arsyeja e anulimit',
  confirmVoid: 'Anulo',
  cancel: 'Mbyll',
  all: 'Të gjitha',
  stock: 'Stoku',
  stockTitle: 'Stoku i produkteve',
  low: 'Stok i ulët',
  add: 'Shto',
  method: { cash: 'Cash', card: 'Kartë', room_charge: 'Në dhomë' } as Record<string, string>,
  payTitle: 'Pagesa',
  roomSearch: 'Numri i dhomës ose mbiemri…',
  pickGuest: 'Zgjidh mysafirin brenda',
  noGuests: 'Asnjë mysafir brenda.',
  charged: 'U ngarkua në faturën e dhomës.',
  paid: 'U pagua.',
  errors: {
    invalid: 'Kontrollo fushat.', forbidden: 'Nuk ke leje për këtë veprim.', module: 'Moduli është i çaktivizuar.', notFound: 'Nuk u gjet.',
    badProduct: 'Një produkt nuk është më i disponueshëm.', discountLimit: 'Zbritja kërkon aprovim menaxheri.', badStatus: 'Porosia nuk mund të ndryshohet tani.',
    emptyOrder: 'Porosia është bosh.', bookingRequired: 'Zgjidh mysafirin.', notInHouse: 'Ky mysafir nuk është brenda.', unknown: 'Diçka shkoi keq.',
  } as Record<string, string>,
};

const en: typeof sq = {
  eyebrow: 'Bar, restaurant and pool',
  title: 'The order goes, the billing follows.',
  subtitle: 'Take the order, send it to the kitchen, and charge it to the guest’s room in one click.',
  today: 'Today',
  sales: 'Sales',
  orders: 'orders',
  tables: 'Tables',
  noTable: 'No table',
  seats: 'seats',
  free: 'free',
  open: 'open',
  order: 'Order',
  empty: 'Pick products from the menu.',
  covers: 'Covers',
  discount: 'Discount %',
  discountHint: (n) => `Above ${n}% needs a manager`,
  subtotal: 'Subtotal',
  total: 'Total',
  send: 'Send to kitchen',
  sent: 'Sent.',
  saved: 'Saved.',
  pay: 'Pay',
  void: 'Void order',
  voidReason: 'Reason for voiding',
  confirmVoid: 'Void',
  cancel: 'Close',
  all: 'All',
  stock: 'Stock',
  stockTitle: 'Product stock',
  low: 'Low stock',
  add: 'Add',
  method: { cash: 'Cash', card: 'Card', room_charge: 'Room charge' },
  payTitle: 'Payment',
  roomSearch: 'Room number or last name…',
  pickGuest: 'Pick the in-house guest',
  noGuests: 'No guests in house.',
  charged: 'Charged to the room folio.',
  paid: 'Paid.',
  errors: {
    invalid: 'Check the fields.', forbidden: 'You are not allowed to do this.', module: 'This module is disabled.', notFound: 'Not found.',
    badProduct: 'A product is no longer available.', discountLimit: 'This discount needs manager approval.', badStatus: 'The order cannot be changed now.',
    emptyOrder: 'The order is empty.', bookingRequired: 'Pick the guest.', notInHouse: 'This guest is not in house.', unknown: 'Something went wrong.',
  },
};

export const pickPosCopy = makeCopy(sq, en);
