import { makeCopy } from '@/lib/copy';

const sq = {
  back: 'Të gjithë mysafirët',
  memberSince: (d: string) => `Njihet që nga ${d}`,
  tier: { platinum: 'Platinum', gold: 'Gold', silver: 'Silver', bronze: 'Bronze', new: 'I ri' } as Record<string, string>,
  segment: { vip: 'VIP', returning: 'Rikthehet', family: 'Familje', long_stay: 'Qëndrime të gjata', big_spender: 'Shpenzon shumë', direct_booker: 'Rezervon direkt', ota_loyal: 'Vjen nga OTA', at_risk: 'Rrezik humbjeje', prospect: 'Ende pa qëndrim' } as Record<string, string>,
  actions: { book: 'Rezervim i ri', whatsapp: 'WhatsApp', call: 'Telefono', email: 'Email', edit: 'Ndrysho', vipOn: 'Bëje VIP', vipOff: 'Hiq VIP', export: 'Eksporto të dhënat', anonymize: 'Fshi të dhënat personale' },
  bookPrompt: (name: string, gid: string) => `Krijo një rezervim të ri për mysafirin ${name} (guest_id ${gid}). Kontrollo disponueshmërinë dhe pyetmë për datat dhe llojin e dhomës.`,
  stats: { stays: 'Qëndrime', nights: 'Net', lifetime: 'Vlera totale', avgNight: 'Mesatarja / natë', extras: 'Shpenzime shtesë', score: 'Gjasat të rikthehet' },
  banners: {
    inHouse: (room: string, out: string) => `Brenda tani${room ? ` në dhomën ${room}` : ''} · largohet ${out}`,
    balance: (m: string) => `Për t’u paguar: ${m}`,
    next: (d: number, type: string) => (d === 0 ? `Mbërrin SOT · ${type}` : d === 1 ? `Mbërrin nesër · ${type}` : `Mbërrin pas ${d} ditësh · ${type}`),
    birthday: (d: number, age: number) => (d === 0 ? `Sot ka ditëlindjen (${age}) 🎂` : `Ditëlindja pas ${d} ditësh (${age})`),
    atRisk: (d: number) => `Nuk ka ardhur prej ${d} ditësh. Mos e humb.`,
    allergies: 'Alergji',
    openBooking: 'Hap rezervimin',
    prepare: 'Përgatit surprizë',
    winBack: 'Shkruaji me AI',
  },
  tabs: { activity: 'Aktiviteti', stays: 'Qëndrimet', spend: 'Shpenzimet', preferences: 'Preferencat', messages: 'Mesazhet', notes: 'Shënimet', privacy: 'Privatësia' },
  filters: { all: 'Të gjitha', bookings: 'Rezervime', money: 'Para', spa: 'Spa', messages: 'Biseda', notes: 'Shënime' },
  more: 'Shfaq më shumë',
  emptyActivity: 'Ende asnjë aktivitet.',
  tl: {
    created: (type: string) => `Rezervoi ${type}`,
    cancelled: (code: string) => `Anuloi rezervimin ${code}`,
    in: (room: string) => `Hyri${room ? ` në dhomën ${room}` : ''}`,
    out: (room: string) => `Doli${room ? ` nga dhoma ${room}` : ''}`,
    payment: 'Pagesë', refund: 'Rimbursim', deposit: 'Paradhënie',
    spa: (n: string) => `Spa: ${n}`,
    msgGuest: (ch: string) => `Shkroi në ${ch}`, msgAi: (ch: string) => `AI u përgjigj në ${ch}`, msgStaff: (ch: string) => `Stafi u përgjigj në ${ch}`, msgSystem: (ch: string) => `Mesazh automatik në ${ch}`,
    call: (min: number) => `Telefonatë me asistentin zanor · ${min} min`,
    invoice: (n: string) => `Fatura #${n}`,
    note: (a: string) => `Shënim nga ${a || 'stafi'}`,
    profile: { 'guest.updated': 'Profili u përditësua', 'guest.merged': 'Profilet u bashkuan', 'guest.vip_on': 'U bë VIP', 'guest.vip_off': 'U hoq VIP', 'guest.consent_given': 'Dha pëlqimin për marketing', 'guest.consent_withdrawn': 'Tërhoqi pëlqimin', 'guest.tags_updated': 'Etiketat u ndryshuan', 'guest.preferences_updated': 'Preferencat u përditësuan', 'checkin.document_scanned': 'Dokumenti u skanua në WhatsApp', 'guest.anonymized': 'Të dhënat u fshinë (GDPR)' } as Record<string, string>,
    by: (a: string) => (a ? ` · ${a}` : ''),
  },
  stays: { favRoom: 'Dhoma e preferuar', favType: 'Lloji i preferuar', channel: 'Kanali kryesor', lead: 'Rezervon', leadDays: (d: number) => `${d} ditë përpara`, avgNights: 'Qëndrim mesatar', nights: (n: number) => (n === 1 ? '1 natë' : `${n} net`), season: 'Kur vjen gjatë vitit', extras: 'shtesa', empty: 'Asnjë rezervim.', cancelled: 'anulime', noShows: 'mos-ardhje', people: (a: number, c: number) => `${a} të rritur${c ? ` · ${c} fëmijë` : ''}` },
  months: ['Jan', 'Shk', 'Mar', 'Pri', 'Maj', 'Qer', 'Kor', 'Gus', 'Sht', 'Tet', 'Nën', 'Dhj'],
  spend: { title: 'Ku i shpenzon paratë', favourites: 'Çfarë porosit më shumë', perStay: 'Mesatarisht për qëndrim', empty: 'Ende pa shpenzime.', times: (n: number) => `×${n}` },
  spendType: { room: 'Dhoma', restaurant: 'Restoranti', bar: 'Bari', pool_bar: 'Bari i pishinës', room_service: 'Shërbim në dhomë', spa: 'Spa', minibar: 'Minibari', service: 'Shërbime', discount: 'Zbritje', tax: 'Taksa' } as Record<string, string>,
  prefs: {
    title: 'Çfarë i pëlqen', hint: 'Kliko për të shtuar ose hequr. Recepsioni dhe AI i shohin në çdo qëndrim.', save: 'Ruaj preferencat', saved: 'U ruajt ✓', add: 'Shto…',
    cats: { room: 'Dhoma', pillow: 'Jastëku & shtrati', dietary: 'Ushqimi', allergies: 'Alergji', interests: 'Interesa', transport: 'Transporti' } as Record<string, string>,
    suggest: {
      room: ['Kat i lartë', 'Pamje nga deti', 'Larg ashensorit', 'Dhomë e qetë', 'Dy shtretër', 'Shtrat dopio', 'Ballkon', 'Pranë pishinës'],
      pillow: ['Jastëk i butë', 'Jastëk i fortë', 'Jastëk shtesë', 'Batanije shtesë', 'Pa pupla'],
      dietary: ['Vegjetarian', 'Vegan', 'Halal', 'Pa gluten', 'Pa laktozë', 'Kafe e zezë', 'Mëngjes në dhomë'],
      allergies: ['Arra', 'Kikirikë', 'Fruta deti', 'Gluten', 'Laktozë', 'Pupla', 'Pluhur'],
      interests: ['Spa', 'Verë', 'Plazh', 'Ecje në mal', 'Gatim tradicional', 'Kulturë', 'Fëmijë', 'Biznes'],
      transport: ['Transfertë nga aeroporti', 'Parkim', 'Makinë me qira', 'Taksi'],
    } as Record<string, string[]>,
    occasions: 'Data të veçanta', occasionLabel: 'P.sh. përvjetori i martesës', occasionDate: 'MM-DD',
  },
  messages: { empty: 'Ende pa biseda.', open: 'Hap në kutinë e mesazheve' },
  notes: { placeholder: 'Shkruaj një shënim për stafin (p.sh. “Pëlqen dhomën 204, vjen gjithmonë me qenin”)…', add: 'Shto shënim', pin: 'Ngul lart', unpin: 'Hiq nga lart', delete: 'Fshi', empty: 'Asnjë shënim ende.', pinned: 'I ngulur' },
  privacy: {
    consent: 'Pëlqim për marketing', consentHint: 'Pa pëlqim, sistemi nuk i dërgon oferta.', retention: 'Dokumenti i identitetit fshihet automatikisht', noDoc: 'Asnjë foto dokumenti e ruajtur.', exportHint: 'Gjithçka që dimë për këtë mysafir, në një skedar (neni 15 dhe 20 GDPR).',
    anonymizeHint: 'Fshin emrin, kontaktet, dokumentin, preferencat dhe shënimet. Rezervimet dhe faturat mbeten pa emër, siç kërkon ligji tatimor.', confirmAnonymize: 'Po, fshi të dhënat', cancel: 'Anulo', sure: 'Je i sigurt? Kjo nuk kthehet mbrapsht.',
  },
  side: {
    brief: 'Përmbledhja AI', briefHint: 'Çfarë duhet të dijë stafi para se ta takojë.', generate: 'Gjenero', regenerate: 'Rigjenero',
    compose: 'Mesazh personal', composeHint: 'AI shkruan një mesazh nga historia e tij reale.', copy: 'Kopjo', copied: 'U kopjua', sendWa: 'Dërgo në WhatsApp', sendEmail: 'Dërgo me email',
    purposes: { welcome_back: 'Mirë se u ktheve', win_back: 'Ktheje prapë', birthday: 'Ditëlindje', pre_arrival: 'Para mbërritjes', thank_you: 'Faleminderit', upsell: 'Ofertë' } as Record<string, string>,
    duplicates: 'Profile të dyfishta', dupHint: 'I njëjti mysafir, i ruajtur dy herë. Bashkoji që historia të jetë e plotë.', merge: 'Bashko këtu', mergeConfirm: (a: string) => `Bashko “${a}” në këtë profil? Rezervimet, bisedat dhe faturat kalojnë këtu.`, why: { email: 'email', phone: 'telefon', document: 'dokument', name: 'emër' } as Record<string, string>, noDup: 'Asnjë dyfishim. Profili është i pastër ✓',
    completeness: 'Profili i plotë', missing: 'Mungon', fields: { email: 'Email', phone: 'Telefon', nationality: 'Shtetësi', dateOfBirth: 'Datëlindje', document: 'Dokument', address: 'Adresë', language: 'Gjuhë', preferences: 'Preferenca', consent: 'Pëlqim marketingu' } as Record<string, string>,
    tags: 'Etiketat', addTag: 'Etiketë e re…', facts: 'Faktet', language: 'Gjuha', cancellations: 'Anulime', noShows: 'Mos-ardhje', bookings: 'Rezervime gjithsej',
  },
  edit: { title: 'Ndrysho profilin', firstName: 'Emri', lastName: 'Mbiemri', email: 'Email', phone: 'Telefoni', nationality: 'Shtetësia (p.sh. AL, IT)', language: 'Gjuha (sq, en, it…)', dateOfBirth: 'Datëlindja', documentType: 'Lloji i dokumentit', documentNumber: 'Nr. i dokumentit', address: 'Adresa', city: 'Qyteti', country: 'Shteti', save: 'Ruaj', cancel: 'Anulo' },
  status: { tentative: 'Në pritje', confirmed: 'Konfirmuar', checked_in: 'Brenda', checked_out: 'Përfunduar', cancelled: 'Anuluar', no_show: 'Nuk erdhi' } as Record<string, string>,
  errors: { notFound: 'Nuk u gjet.', forbidden: 'Nuk ke leje.', aiOff: 'AI nuk është konfiguruar.', aiLimit: 'Kufiri orar i AI u arrit.', activeBooking: 'Ka rezervime aktive. Përfundoji ose anuloji fillimisht.', invalid: 'Kontrollo fushat.', unknown: 'Diçka shkoi keq.', module: 'Moduli është i çaktivizuar.' } as Record<string, string>,
};

const en: typeof sq = {
  back: 'All guests',
  memberSince: (d) => `Known since ${d}`,
  tier: { platinum: 'Platinum', gold: 'Gold', silver: 'Silver', bronze: 'Bronze', new: 'New' },
  segment: { vip: 'VIP', returning: 'Returning', family: 'Family', long_stay: 'Long stays', big_spender: 'Big spender', direct_booker: 'Books direct', ota_loyal: 'Comes via OTAs', at_risk: 'At risk', prospect: 'No stay yet' },
  actions: { book: 'New booking', whatsapp: 'WhatsApp', call: 'Call', email: 'Email', edit: 'Edit', vipOn: 'Make VIP', vipOff: 'Remove VIP', export: 'Export data', anonymize: 'Erase personal data' },
  bookPrompt: (name, gid) => `Create a new booking for guest ${name} (guest_id ${gid}). Check availability and ask me for the dates and room type.`,
  stats: { stays: 'Stays', nights: 'Nights', lifetime: 'Lifetime value', avgNight: 'Avg per night', extras: 'Extra spend', score: 'Return likelihood' },
  banners: {
    inHouse: (room, out) => `In house now${room ? ` in room ${room}` : ''} · leaves ${out}`,
    balance: (m) => `Balance due: ${m}`,
    next: (d, type) => (d === 0 ? `Arrives TODAY · ${type}` : d === 1 ? `Arrives tomorrow · ${type}` : `Arrives in ${d} days · ${type}`),
    birthday: (d, age) => (d === 0 ? `Birthday today (${age}) 🎂` : `Birthday in ${d} days (${age})`),
    atRisk: (d) => `Hasn't been back for ${d} days. Don't lose them.`,
    allergies: 'Allergies',
    openBooking: 'Open booking',
    prepare: 'Prepare a surprise',
    winBack: 'Write with AI',
  },
  tabs: { activity: 'Activity', stays: 'Stays', spend: 'Spend', preferences: 'Preferences', messages: 'Messages', notes: 'Notes', privacy: 'Privacy' },
  filters: { all: 'All', bookings: 'Bookings', money: 'Money', spa: 'Spa', messages: 'Conversations', notes: 'Notes' },
  more: 'Show more',
  emptyActivity: 'No activity yet.',
  tl: {
    created: (type) => `Booked ${type}`,
    cancelled: (code) => `Cancelled booking ${code}`,
    in: (room) => `Checked in${room ? ` to room ${room}` : ''}`,
    out: (room) => `Checked out${room ? ` of room ${room}` : ''}`,
    payment: 'Payment', refund: 'Refund', deposit: 'Deposit',
    spa: (n) => `Spa: ${n}`,
    msgGuest: (ch) => `Wrote on ${ch}`, msgAi: (ch) => `AI replied on ${ch}`, msgStaff: (ch) => `Staff replied on ${ch}`, msgSystem: (ch) => `Automatic message on ${ch}`,
    call: (min) => `Call with the voice assistant · ${min} min`,
    invoice: (n) => `Invoice #${n}`,
    note: (a) => `Note by ${a || 'staff'}`,
    profile: { 'guest.updated': 'Profile updated', 'guest.merged': 'Profiles merged', 'guest.vip_on': 'Became VIP', 'guest.vip_off': 'VIP removed', 'guest.consent_given': 'Gave marketing consent', 'guest.consent_withdrawn': 'Withdrew consent', 'guest.tags_updated': 'Tags changed', 'guest.preferences_updated': 'Preferences updated', 'checkin.document_scanned': 'Document scanned on WhatsApp', 'guest.anonymized': 'Personal data erased (GDPR)' },
    by: (a) => (a ? ` · ${a}` : ''),
  },
  stays: { favRoom: 'Favourite room', favType: 'Favourite type', channel: 'Main channel', lead: 'Books', leadDays: (d) => `${d} days ahead`, avgNights: 'Average stay', nights: (n) => (n === 1 ? '1 night' : `${n} nights`), season: 'When they come during the year', extras: 'extras', empty: 'No bookings.', cancelled: 'cancellations', noShows: 'no-shows', people: (a, c) => `${a} adults${c ? ` · ${c} children` : ''}` },
  months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  spend: { title: 'Where the money goes', favourites: 'What they order most', perStay: 'Average per stay', empty: 'No spend yet.', times: (n) => `×${n}` },
  spendType: { room: 'Room', restaurant: 'Restaurant', bar: 'Bar', pool_bar: 'Pool bar', room_service: 'Room service', spa: 'Spa', minibar: 'Minibar', service: 'Services', discount: 'Discounts', tax: 'Taxes' },
  prefs: {
    title: 'What they like', hint: 'Click to add or remove. Front desk and the AI see these on every stay.', save: 'Save preferences', saved: 'Saved ✓', add: 'Add…',
    cats: { room: 'Room', pillow: 'Pillow & bed', dietary: 'Food', allergies: 'Allergies', interests: 'Interests', transport: 'Transport' },
    suggest: {
      room: ['High floor', 'Sea view', 'Away from lift', 'Quiet room', 'Twin beds', 'Double bed', 'Balcony', 'Near the pool'],
      pillow: ['Soft pillow', 'Firm pillow', 'Extra pillow', 'Extra blanket', 'No feathers'],
      dietary: ['Vegetarian', 'Vegan', 'Halal', 'Gluten free', 'Lactose free', 'Black coffee', 'Breakfast in room'],
      allergies: ['Nuts', 'Peanuts', 'Seafood', 'Gluten', 'Lactose', 'Feathers', 'Dust'],
      interests: ['Spa', 'Wine', 'Beach', 'Hiking', 'Local cooking', 'Culture', 'Kids', 'Business'],
      transport: ['Airport transfer', 'Parking', 'Car rental', 'Taxi'],
    },
    occasions: 'Special dates', occasionLabel: 'E.g. wedding anniversary', occasionDate: 'MM-DD',
  },
  messages: { empty: 'No conversations yet.', open: 'Open in inbox' },
  notes: { placeholder: 'Write a note for the team (e.g. “Loves room 204, always travels with the dog”)…', add: 'Add note', pin: 'Pin', unpin: 'Unpin', delete: 'Delete', empty: 'No notes yet.', pinned: 'Pinned' },
  privacy: {
    consent: 'Marketing consent', consentHint: 'Without consent the system sends no offers.', retention: 'Identity document is deleted automatically', noDoc: 'No document photo stored.', exportHint: 'Everything we know about this guest, in one file (GDPR articles 15 and 20).',
    anonymizeHint: 'Erases name, contacts, document, preferences and notes. Bookings and invoices stay without a name, as tax law requires.', confirmAnonymize: 'Yes, erase the data', cancel: 'Cancel', sure: 'Are you sure? This cannot be undone.',
  },
  side: {
    brief: 'AI brief', briefHint: 'What the team should know before meeting them.', generate: 'Generate', regenerate: 'Regenerate',
    compose: 'Personal message', composeHint: 'The AI writes a message from their real history.', copy: 'Copy', copied: 'Copied', sendWa: 'Send on WhatsApp', sendEmail: 'Send by email',
    purposes: { welcome_back: 'Welcome back', win_back: 'Win back', birthday: 'Birthday', pre_arrival: 'Pre-arrival', thank_you: 'Thank you', upsell: 'Offer' },
    duplicates: 'Duplicate profiles', dupHint: 'The same guest stored twice. Merge them so the history is complete.', merge: 'Merge here', mergeConfirm: (a) => `Merge “${a}” into this profile? Bookings, conversations and invoices move here.`, why: { email: 'email', phone: 'phone', document: 'document', name: 'name' }, noDup: 'No duplicates. The profile is clean ✓',
    completeness: 'Profile completeness', missing: 'Missing', fields: { email: 'Email', phone: 'Phone', nationality: 'Nationality', dateOfBirth: 'Date of birth', document: 'Document', address: 'Address', language: 'Language', preferences: 'Preferences', consent: 'Marketing consent' },
    tags: 'Tags', addTag: 'New tag…', facts: 'Facts', language: 'Language', cancellations: 'Cancellations', noShows: 'No-shows', bookings: 'Total bookings',
  },
  edit: { title: 'Edit profile', firstName: 'First name', lastName: 'Last name', email: 'Email', phone: 'Phone', nationality: 'Nationality (e.g. AL, IT)', language: 'Language (sq, en, it…)', dateOfBirth: 'Date of birth', documentType: 'Document type', documentNumber: 'Document number', address: 'Address', city: 'City', country: 'Country', save: 'Save', cancel: 'Cancel' },
  status: { tentative: 'Tentative', confirmed: 'Confirmed', checked_in: 'In house', checked_out: 'Completed', cancelled: 'Cancelled', no_show: 'No-show' },
  errors: { notFound: 'Not found.', forbidden: 'Not allowed.', aiOff: 'AI is not configured.', aiLimit: 'Hourly AI limit reached.', activeBooking: 'There are active bookings. Complete or cancel them first.', invalid: 'Check the fields.', unknown: 'Something went wrong.', module: 'Module disabled.' },
};

export const pickProfileCopy = makeCopy(sq, en);
export type ProfileCopy = typeof sq;
