const sq = {
  eyebrow: 'Rezervimet · recepsioni',
  title: 'Çdo mbërritje, e pritur.',
  subtitle: 'Mbërritjet, mysafirët brenda, largimet dhe pagesat, të lidhura me dhomat reale.',
  views: { arrivals: 'Mbërrijnë sot', inhouse: 'Brenda', departures: 'Largohen', upcoming: 'Në ardhje', all: 'Të gjitha' },
  search: 'Kërko emër, kod, telefon…',
  newBooking: 'Rezervim i ri',
  empty: 'Asnjë rezervim këtu.',
  nights: (n: number) => (n === 1 ? '1 natë' : `${n} net`),
  people: (a: number, c: number) => `${a} të rritur${c ? ` · ${c} fëmijë` : ''}`,
  unassigned: 'Pa dhomë',
  room: 'Dhoma',
  total: 'Qëndrimi',
  extras: 'Shtesa',
  paid: 'Paguar',
  balance: 'Për t’u paguar',
  settled: 'E shlyer',
  close: 'Mbyll',
  profile: 'Profili i mysafirit',
  status: { tentative: 'Në pritje', confirmed: 'Konfirmuar', checked_in: 'Brenda', checked_out: 'Larguar', cancelled: 'Anuluar', no_show: 'Nuk erdhi' },
  source: { direct: 'Direkt', website: 'Faqja', booking_com: 'Booking.com', airbnb: 'Airbnb', expedia: 'Expedia', agoda: 'Agoda', whatsapp: 'WhatsApp', instagram: 'Instagram', messenger: 'Messenger', phone: 'Telefon', ai_voice: 'Asistenti zanor', walk_in: 'Pa rezervim' },
  form: {
    title: 'Rezervim i ri', stay: 'Qëndrimi', guest: 'Mysafiri', roomType: 'Lloji i dhomës', checkIn: 'Mbërritja', checkOut: 'Largimi',
    adults: 'Të rritur', children: 'Fëmijë', source: 'Burimi', status: 'Statusi', firstName: 'Emri', lastName: 'Mbiemri',
    email: 'Email', phone: 'Telefoni', nationality: 'Shtetësia', eta: 'Ora e mbërritjes', requests: 'Kërkesa të veçanta',
    price: 'Çmim i negociuar (opsional)', autoAssign: 'Cakto dhomën automatikisht', create: 'Krijo rezervimin',
    quoting: 'Po llogaris…', left: (n: number) => (n === 1 ? 'Mbetet 1 dhomë' : `Mbeten ${n} dhoma`), perNight: 'mesatarisht / natë',
    dedupe: 'Nëse email-i ose telefoni ekziston, përdoret profili ekzistues.',
  },
  actions: {
    confirm: 'Konfirmo', checkIn: 'Regjistro hyrjen', checkOut: 'Regjistro daljen', forceCheckOut: 'Dil me borxh (menaxher)',
    cancel: 'Anulo', noShow: 'Nuk erdhi', reason: 'Arsyeja e anulimit', confirmCancel: 'Anulo rezervimin', back: 'Kthehu',
    assign: 'Cakto dhomën', whatsapp: 'WhatsApp', call: 'Telefono',
  },
  pay: { title: 'Pagesë', amount: 'Shuma', method: 'Mënyra', refund: 'Rimbursim', reference: 'Referenca', submit: 'Regjistro pagesën', methods: { cash: 'Cash', card: 'Kartë', bank_transfer: 'Bankë', online: 'Online', room_charge: 'Në dhomë' } },
  charge: { title: 'Shto shpenzim', description: 'Përshkrimi', qty: 'Sasia', price: 'Çmimi', submit: 'Shto në faturë', void: 'Anulo', types: { room: 'Dhoma', restaurant: 'Restoranti', bar: 'Bari', pool_bar: 'Bari i pishinës', room_service: 'Shërbim në dhomë', spa: 'Spa', minibar: 'Minibari', service: 'Shërbim', tax: 'Taksë', discount: 'Zbritje' } },
  sections: { guest: 'Mysafiri', stay: 'Qëndrimi', money: 'Llogaria', folio: 'Fatura e dhomës', payments: 'Pagesat', timeline: 'Historiku' },
  timeline: {
    'booking.created': 'Rezervimi u krijua', 'booking.confirmed': 'U konfirmua', 'booking.room_assigned': 'U caktua dhoma',
    'booking.room_unassigned': 'U hoq dhoma', 'booking.upgraded': 'U përmirësua dhoma', 'booking.checked_in': 'Hyri',
    'booking.checked_out': 'Doli', 'booking.cancelled': 'U anulua', 'booking.no_show': 'Nuk erdhi',
'payment.recorded': 'Pagesë', 'payment.refunded': 'Rimbursim', 'folio.charge_posted': 'Shpenzim i shtuar', 'folio.charge_voided': 'Shpenzim i anuluar', 'booking.stay_changed': 'U ndryshua qëndrimi', 'booking.channel_created': 'Erdhi nga kanali', 'booking.channel_modified': 'U ndryshua nga kanali',  } as Record<string, string>,
  errors: {
    invalid: 'Kontrollo fushat.', forbidden: 'Kjo kërkon leje menaxheri.', module: 'Moduli është i çaktivizuar.', unknown: 'Diçka shkoi keq. Provo përsëri.',
    notFound: 'Rezervimi nuk u gjet.', nights: 'Qëndrimi duhet të jetë 1–60 net.', type: 'Lloji i dhomës nuk është aktiv.',
    closed: 'Një nga netët është e mbyllur për shitje.', minStay: 'Nuk plotësohet qëndrimi minimal.', soldOut: 'Nuk ka dhoma të lira për këto data.',
    occupancy: 'Shumë persona për këtë lloj dhome.', pastDate: 'Mbërritja nuk mund të jetë në të kaluarën.', guestRequired: 'Shto mysafirin.',
    guestNotFound: 'Mysafiri nuk u gjet.', roomTaken: 'Dhoma është e zënë për këto data.', roomNotReady: 'Dhoma nuk është e pastër ende.',
    noRoom: 'Nuk ka dhomë të lirë për caktim.', notConfirmed: 'Konfirmo rezervimin fillimisht.', badStatus: 'Ky veprim nuk lejohet në këtë status.',
    tooEarly: 'Mbërritja nuk është ende.', stayOver: 'Data e largimit ka kaluar.', balanceDue: 'Ka ende shumë për t’u paguar.',
    refundTooLarge: 'Rimbursimi është më i madh se shuma e paguar.', notInHouse: 'Mysafiri nuk është brenda.', duplicate: 'Ekziston tashmë.',
    email: 'Email i pavlefshëm.', roomInvalid: 'Dhomë e pavlefshme.', alreadyVoided: 'Ky shpenzim është anuluar tashmë.',
  } as Record<string, string>,
};

const en: typeof sq = {
  eyebrow: 'Bookings · front desk',
  title: 'Every arrival, expected.',
  subtitle: 'Arrivals, in-house guests, departures and payments, tied to real rooms.',
  views: { arrivals: 'Arriving today', inhouse: 'In house', departures: 'Departing', upcoming: 'Upcoming', all: 'All' },
  search: 'Search name, code, phone…',
  newBooking: 'New booking',
  empty: 'No bookings here.',
  nights: (n) => (n === 1 ? '1 night' : `${n} nights`),
  people: (a, c) => `${a} adult${a === 1 ? '' : 's'}${c ? ` · ${c} child${c === 1 ? '' : 'ren'}` : ''}`,
  unassigned: 'Unassigned',
  room: 'Room',
  total: 'Stay',
  extras: 'Extras',
  paid: 'Paid',
  balance: 'Balance due',
  settled: 'Settled',
  close: 'Close',
  profile: 'Guest profile',
  status: { tentative: 'Tentative', confirmed: 'Confirmed', checked_in: 'In house', checked_out: 'Checked out', cancelled: 'Cancelled', no_show: 'No-show' },
  source: { direct: 'Direct', website: 'Website', booking_com: 'Booking.com', airbnb: 'Airbnb', expedia: 'Expedia', agoda: 'Agoda', whatsapp: 'WhatsApp', instagram: 'Instagram', messenger: 'Messenger', phone: 'Phone', ai_voice: 'Voice AI', walk_in: 'Walk-in' },
  form: {
    title: 'New booking', stay: 'Stay', guest: 'Guest', roomType: 'Room type', checkIn: 'Arrival', checkOut: 'Departure',
    adults: 'Adults', children: 'Children', source: 'Source', status: 'Status', firstName: 'First name', lastName: 'Last name',
    email: 'Email', phone: 'Phone', nationality: 'Nationality', eta: 'Arrival time', requests: 'Special requests',
    price: 'Negotiated price (optional)', autoAssign: 'Assign a room automatically', create: 'Create booking',
    quoting: 'Calculating…', left: (n) => (n === 1 ? '1 room left' : `${n} rooms left`), perNight: 'avg / night',
    dedupe: 'If the email or phone already exists, the existing guest profile is reused.',
  },
  actions: {
    confirm: 'Confirm', checkIn: 'Check in', checkOut: 'Check out', forceCheckOut: 'Check out with balance (manager)',
    cancel: 'Cancel', noShow: 'No-show', reason: 'Cancellation reason', confirmCancel: 'Cancel booking', back: 'Back',
    assign: 'Assign room', whatsapp: 'WhatsApp', call: 'Call',
  },
  pay: { title: 'Payment', amount: 'Amount', method: 'Method', refund: 'Refund', reference: 'Reference', submit: 'Record payment', methods: { cash: 'Cash', card: 'Card', bank_transfer: 'Bank transfer', online: 'Online', room_charge: 'Room charge' } },
  charge: { title: 'Add charge', description: 'Description', qty: 'Qty', price: 'Price', submit: 'Post to folio', void: 'Void', types: { room: 'Room', restaurant: 'Restaurant', bar: 'Bar', pool_bar: 'Pool bar', room_service: 'Room service', spa: 'Spa', minibar: 'Minibar', service: 'Service', tax: 'Tax', discount: 'Discount' } },
  sections: { guest: 'Guest', stay: 'Stay', money: 'Account', folio: 'Folio', payments: 'Payments', timeline: 'Timeline' },
  timeline: {
    'booking.created': 'Booking created', 'booking.confirmed': 'Confirmed', 'booking.room_assigned': 'Room assigned',
    'booking.room_unassigned': 'Room unassigned', 'booking.upgraded': 'Upgraded', 'booking.checked_in': 'Checked in',
    'booking.checked_out': 'Checked out', 'booking.cancelled': 'Cancelled', 'booking.no_show': 'No-show',
'payment.recorded': 'Payment', 'payment.refunded': 'Refund', 'folio.charge_posted': 'Charge posted', 'folio.charge_voided': 'Charge voided',     'booking.stay_changed': 'Stay changed',     'booking.channel_created': 'Received from channel', 'booking.channel_modified': 'Modified by channel',  },
  errors: {
    invalid: 'Please check the fields.', forbidden: 'This needs manager permission.', module: 'Module disabled.', unknown: 'Something went wrong. Try again.',
    notFound: 'Booking not found.', nights: 'Stay must be 1–60 nights.', type: 'Room type is not active.',
    closed: 'One of the nights is closed for sale.', minStay: 'Minimum stay not met.', soldOut: 'No rooms available for these dates.',
    occupancy: 'Too many guests for this room type.', pastDate: 'Arrival cannot be in the past.', guestRequired: 'Add the guest.',
    guestNotFound: 'Guest not found.', roomTaken: 'That room is taken for these dates.', roomNotReady: 'Room is not clean yet.',
    noRoom: 'No free room to assign.', notConfirmed: 'Confirm the booking first.', badStatus: 'Not allowed in this status.',
    tooEarly: 'Arrival date has not come yet.', stayOver: 'Departure date has passed.', balanceDue: 'There is still a balance due.',
    refundTooLarge: 'Refund exceeds the amount paid.', notInHouse: 'Guest is not in house.', duplicate: 'Already exists.',
    email: 'Invalid email.', roomInvalid: 'Invalid room.', alreadyVoided: 'Already voided.',
  },
};

export const bookingCopy = { sq, en };
export type BookingCopy = typeof sq;
export const pickCopy = (locale: string) => (locale === 'en' ? en : sq);
