import { makeCopy } from '@/lib/copy';

const sq = {
  nav: { features: 'Veçoritë', how: 'Si punon', pricing: 'Çmimet', faq: 'Pyetje', demo: 'Provo demon' },
  hero: {
    eyebrow: 'Sistemi i parë shqiptar për hotele, i ndërtuar me AI',
    title: ['Hoteli yt.', 'Një mendje', 'që nuk fle.'],
    sub: 'Rezervime, kalendar, mesazhe, faturë e fiskalizuar dhe një AI që flet shqip me mysafirët e që t’u përgjigjet ty për çdo gjë në biznesin tënd.',
    cta: 'Provo demon live',
    cta2: 'Shiko faqen e një resorti',
    note: 'Pa kartë. Hyn me një klik në Vala Resort & Spa (hotel fiktiv).',
  },
  cards: {
    brief: { title: 'Përmbledhja e mëngjesit', text: 'Mirëmëngjes, Dritan. Dje fituat 4.280 €, 12% më shumë se java e kaluar. Sot mbërrijnë 9 rezervime, dy prej tyre VIP.' },
    chat: { guest: 'A keni dhomë të lirë për 14–17 gusht, me pamje nga deti?', ai: 'Po! Kam Deluxe me pamje nga deti për 3 net: 540 €. Ta rezervoj për ju?' },
    calendar: 'Kalendari që lëviz me gishta',
  },
  stats: [
    { value: 24, suffix: '/7', label: 'AI që u përgjigjet mysafirëve shqip e anglisht' },
    { value: 0, suffix: '%', label: 'komision në rezervimet direkte nga faqja jote' },
    { value: 14, suffix: '', label: 'module, të ndezura vetëm ato që të duhen' },
    { value: 3, suffix: ' min', label: 'kohë për një rezervim nga telefoni' },
  ],
  features: {
    eyebrow: 'Çfarë bën',
    title: 'Gjithçka që një hotel ka nevojë, në një ekran.',
    items: [
      { key: 'ask', title: 'Pyet hotelin', text: 'Shkruaj “sa fitoi bari këtë javë?” dhe merr përgjigjen me numra e grafik në sekonda. Pa Excel, pa pritje.', big: true },
      { key: 'calendar', title: 'Kalendar me tërheq-e-lësho', text: 'Të gjitha dhomat dhe rezervimet ditë pas dite. Zhvendos një mysafir me një lëvizje, zgjat një qëndrim duke tërhequr skajin.' },
      { key: 'channels', title: 'Kanalet e lidhura', text: 'Booking.com, Airbnb, Expedia: sinkronizim iCal falas, ose në kohë reale si shtesë. Mbi-rezervimet të bien në sy para se të ndodhin.' },
      { key: 'inbox', title: 'Një kuti mesazhesh', text: 'WhatsApp, Instagram, Messenger dhe chat-i i faqes. AI përgjigjet vetë, ti merr bisedën kur do.', big: true },
      { key: 'pos', title: 'Bar, restorant, pishinë', text: 'Porosia shkon te kuzhina dhe faturohet në dhomën e mysafirit me një klik.' },
      { key: 'fiscal', title: 'Faturë e fiskalizuar', text: 'NIVF, NSLF dhe kod QR për çdo faturë. Gati për easyPos dhe fature.al.' },
      { key: 'ocr', title: 'Foto e faturës, gati shpenzimi', text: 'Fotografo faturën e furnitorit. AI lexon shumën, TVSH-në dhe kategorinë.' },
      { key: 'voice', title: 'Telefonata me AI', text: 'Merr telefonatat në shqip, kontrollon disponueshmërinë dhe rezervon. Të lidh me recepsionin kur duhet.' },
      { key: 'alerts', title: 'Alarme kundër mashtrimit', text: 'Zbritje të pazakonta, anulime të përsëritura, diferenca në arkë: ti i mëson para se të bëhen problem.' },
    ],
  },
  how: {
    eyebrow: 'Si punon',
    title: 'Nga zero te hoteli i lidhur, në një pasdite.',
    steps: [
      { n: '01', title: 'Na tregon hotelin', text: 'Dhomat, çmimet dhe ekipi. Ne e vendosim gjithçka dhe të japim një faqe rezervimi të gatshme.' },
      { n: '02', title: 'Lidh kanalet', text: 'Ngjit lidhjet iCal të Booking.com dhe Airbnb dhe kalendari yt bëhet një. Aktivizon WhatsApp kur të jesh gati.' },
      { n: '03', title: 'Lëre AI-në të punojë', text: 'Ajo u përgjigjet mysafirëve, të dërgon raportin çdo mëngjes dhe të tregon çfarë të kushton më shumë.' },
    ],
  },
  pricing: {
    eyebrow: 'Çmimet',
    title: 'E thjeshtë, e hapur, pa surpriza.',
    sub: 'Jemi kompani e re shqiptare. Për 50 hotelet e para: çmim themelues, i fiksuar për 2 vjet.',
    per: 'në muaj',
    popular: 'Më i zgjedhuri',
    custom: 'Sipas marrëveshjes',
    cta: 'Fillo me këtë',
    contact: 'Na shkruaj',
    note: 'Çmimet janë në euro në muaj, sipas madhësisë së hotelit. Pagesa vjetore = 2 muaj falas. Instalimi një herë: 149 / 299 / 499 € (import i të dhënave, lidhja e kanaleve, trajnimi). Pagesa fillimisht cash.',
    sizes: { small: '1–15 dhoma', medium: '16–40 dhoma', large: '41–100 dhoma' },
    sizeLabel: 'Sa dhoma ka hoteli yt?',
    founding: (n: number) => `Çmim themelues −30% për ${n} hotelet e para, i fiksuar 2 vjet`,
    was: 'çmimi normal',
    enterpriseFrom: 'Nga 249 € / muaj + instalim',
    addonsTitle: 'Shtesa kur t’i duhen',
    addons: [
      { name: 'Sinkronizim në kohë reale me OTA', text: 'Përfshirë në Signature. Për Essential dhe Professional: çmime e disponueshmëri menjëherë (iCal falas mbetet në çdo plan).', price: '' },
      { name: 'Asistenti zanor me AI', text: '150 minuta përfshirë (100 në Signature), pastaj 0,35 € / minutë.', price: '49 € / muaj' },
      { name: 'WhatsApp', text: 'Mesazhe përfshirë në Profesional e sipër (200 / 600 / 1.500 sipas madhësisë), pastaj 0,04 € / mesazh. Email është falas.', price: 'Përfshirë' },
    ],
    plans: [
      { key: 'basic', name: 'Essential', text: 'Për guesthouse dhe hotele të vogla që duan rregull.', features: ['Recepsioni, rezervimet, kalendari', 'Faqja e rezervimeve pa komision', 'Faturimi i fiskalizuar', 'Raportet', 'Sinkronizim iCal falas me OTA'] },
      { key: 'pro', name: 'Professional', text: 'Hoteli që punon pa stres, me AI në çdo bisedë.', features: ['Gjithçka nga Essential', 'Asistenti AI për mysafirët (WhatsApp, IG, chat)', 'Kutia e përbashkët e mesazheve', 'POS bar & restorant, Spa', 'Shpenzime me foto (OCR) dhe fiskalizim'], popular: true },
      { key: 'premium', name: 'Signature', text: 'Sistemi operativ i plotë: pronari di gjithçka, kanalet punojnë vetë.', features: ['Gjithçka nga Professional', 'Pyet hotelin: AI për pronarin + raporti i mëngjesit', 'Sinkronizim në kohë reale me Booking, Airbnb, Expedia', 'Asistenti zanor me AI (100 min përfshirë)', 'Alarme mashtrimi dhe sugjerime çmimesh'] },
      { key: 'enterprise', name: 'Enterprise', text: 'Resorte dhe grupe: sistemi yt, në serverin tënd.', features: ['I njëjti kod, i personalizuar', 'Server dhe brand i veti', 'Module sipas kërkesës', 'Integrime të veçanta', 'Mirëmbajtje dhe SLA'] },
    ],
  },
  faq: {
    eyebrow: 'Pyetje të shpeshta',
    title: 'Ato që pyesin pronarët.',
    items: [
      { q: 'A është e ligjshme faturimi im?', a: 'Sistemi është ndërtuar për fiskalizim me ofrues të certifikuar (easyPos, fature.al). Çdo hotel ka certifikatën e vet fiskale, si me çdo sistem tjetër. Ne e bëjmë lidhjen dhe e mbajmë të thjeshtë.' },
      { q: 'A lidhet me Booking.com dhe Airbnb?', a: 'Po, me sinkronizim iCal falas (rezervimet hyjnë vetë, datat bllokohen). Për sinkronizim në kohë reale me çmime dhe disponueshmëri ofrojmë një shtesë mujore.' },
      { q: 'A e lexon AI çdo gjë që flasim me mysafirët?', a: 'AI përgjigjet vetëm për çfarë ti i ke lejuar dhe nuk shpik çmime a disponueshmëri. Çdo bisedë e sheh ti dhe mund ta marrësh në dorë kur të duash. Passaportat nuk ruhen si foto.' },
      { q: 'Çfarë ndodh me të dhënat e mysafirëve?', a: 'Serverat janë në Bashkimin Evropian. Të dhënat e dokumenteve fshihen automatikisht pas qëndrimit dhe çdo hotel sheh vetëm të dhënat e veta.' },
      { q: 'Duhet kartë për të paguar?', a: 'Jo. Në fillim pranojmë pagesë cash. Më vonë do të keni edhe pagesë automatike, nëse e doni.' },
      { q: 'Çfarë ndodh nëse s’ka internet?', a: 'Fiskalizimi pa internet është në planin tonë të zhvillimit dhe do t’ju njoftojmë kur të jetë gati. Sot sistemi punon në internet.' },
    ],
  },
  cta: {
    title: 'Le ta provojmë me hotelin tënd.',
    sub: 'Na lër emrin dhe një numër. Të kontaktojmë brenda ditës dhe ta ngrejmë hotelin tënd në sistem pa asnjë kosto fillestare.',
    name: 'Emri yt',
    hotel: 'Hoteli',
    phone: 'Telefoni ose WhatsApp',
    send: 'Dërgo',
    sent: 'Faleminderit! Të kontaktojmë shumë shpejt.',
    error: 'Nuk u dërgua. Shkruaj direkt në WhatsApp ose email.',
    or: 'ose shkruaj direkt',
    whatsapp: 'WhatsApp',
    email: 'Email',
  },
  footer: { made: 'Ndërtuar në Shqipëri, për hotelet shqiptare.', demo: 'Demo', resort: 'Faqja e resortit demo', login: 'Hyrja' },
};

const en: typeof sq = {
  nav: { features: 'Features', how: 'How it works', pricing: 'Pricing', faq: 'FAQ', demo: 'Try the demo' },
  hero: {
    eyebrow: 'The first Albanian hotel system, built with AI',
    title: ['Your hotel.', 'One mind', 'that never sleeps.'],
    sub: 'Bookings, calendar, messages, fiscalized invoices, and an AI that talks to guests in Albanian and answers you about anything in your business.',
    cta: 'Try the live demo',
    cta2: 'See a resort website',
    note: 'No card. One click into Vala Resort & Spa (a fictional hotel).',
  },
  cards: {
    brief: { title: 'Morning briefing', text: 'Good morning, Dritan. Yesterday you earned €4,280, 12% more than last week. 9 bookings arrive today, two of them VIP.' },
    chat: { guest: 'Do you have a sea-view room free for 14–17 August?', ai: 'Yes! A Deluxe sea view for 3 nights is €540. Shall I book it for you?' },
    calendar: 'The calendar you move with your fingers',
  },
  stats: [
    { value: 24, suffix: '/7', label: 'AI answering guests in Albanian and English' },
    { value: 0, suffix: '%', label: 'commission on direct bookings from your site' },
    { value: 14, suffix: '', label: 'modules, switch on only what you need' },
    { value: 3, suffix: ' min', label: 'to take a booking from your phone' },
  ],
  features: {
    eyebrow: 'What it does',
    title: 'Everything a hotel needs, on one screen.',
    items: [
      { key: 'ask', title: 'Ask your hotel', text: 'Type “how much did the bar make this week?” and get the answer with numbers and a chart in seconds. No Excel, no waiting.', big: true },
      { key: 'calendar', title: 'Drag-and-drop calendar', text: 'Every room and booking, day by day. Move a guest with one gesture, stretch a stay by dragging its edge.' },
      { key: 'channels', title: 'Connected channels', text: 'Booking.com, Airbnb, Expedia: free iCal sync, or real-time as an add-on. Overbookings show up before they happen.' },
      { key: 'inbox', title: 'One inbox', text: 'WhatsApp, Instagram, Messenger and website chat. The AI replies by itself, you take over whenever you like.', big: true },
      { key: 'pos', title: 'Bar, restaurant, pool', text: 'Orders go to the kitchen and charge to the guest’s room in one click.' },
      { key: 'fiscal', title: 'Fiscalized invoices', text: 'NIVF, NSLF and a QR code on every invoice. Ready for easyPos and fature.al.' },
      { key: 'ocr', title: 'Photo of a receipt, expense done', text: 'Snap a supplier invoice. The AI reads amount, VAT and category.' },
      { key: 'voice', title: 'AI phone answering', text: 'Answers calls in Albanian, checks availability and books. Hands over to reception when needed.' },
      { key: 'alerts', title: 'Fraud alerts', text: 'Unusual discounts, repeated voids, cash differences: you find out before they become a problem.' },
    ],
  },
  how: {
    eyebrow: 'How it works',
    title: 'From zero to a connected hotel in one afternoon.',
    steps: [
      { n: '01', title: 'Tell us about your hotel', text: 'Rooms, prices and team. We set everything up and give you a booking website that is ready to go.' },
      { n: '02', title: 'Connect your channels', text: 'Paste the iCal links from Booking.com and Airbnb and your calendar becomes one. Switch on WhatsApp when you are ready.' },
      { n: '03', title: 'Let the AI work', text: 'It answers guests, sends you the morning report and shows you what costs you the most.' },
    ],
  },
  pricing: {
    eyebrow: 'Pricing',
    title: 'Simple, open, no surprises.',
    sub: 'We are a new Albanian company. For the first 50 hotels: a founding price, locked for 2 years.',
    per: 'per month',
    popular: 'Most popular',
    custom: 'Custom',
    cta: 'Start with this',
    contact: 'Talk to us',
    note: 'Prices are in euro per month, by hotel size. Annual billing = 2 months free. One-time setup: €149 / €299 / €499 (data import, channel mapping, training). Payment is cash at first.',
    sizes: { small: '1–15 rooms', medium: '16–40 rooms', large: '41–100 rooms' },
    sizeLabel: 'How many rooms does your hotel have?',
    founding: (n: number) => `Founding price −30% for the first ${n} hotels, locked for 2 years`,
    was: 'list price',
    enterpriseFrom: 'From €249 / month + setup',
    addonsTitle: 'Add-ons when you need them',
    addons: [
      { name: 'Real-time OTA sync', text: 'Included in Signature. For Essential and Professional: prices and availability instantly (free iCal stays in every plan).', price: '' },
      { name: 'AI voice assistant', text: '150 minutes included (100 in Signature), then €0.35 / minute.', price: '€49 / month' },
      { name: 'WhatsApp', text: 'Messages included from Professional up (200 / 600 / 1,500 by size), then €0.04 / message. Email is free.', price: 'Included' },
    ],
    plans: [
      { key: 'basic', name: 'Essential', text: 'For guesthouses and small hotels that want order.', features: ['Front desk, bookings, calendar', 'Commission-free booking website', 'Fiscalized invoicing', 'Reports', 'Free iCal sync with OTAs'] },
      { key: 'pro', name: 'Professional', text: 'The hotel that runs stress-free, with AI in every conversation.', features: ['Everything in Essential', 'Guest AI assistant (WhatsApp, IG, chat)', 'Unified inbox', 'Bar & restaurant POS, Spa', 'Photo expenses (OCR) and fiscalization'], popular: true },
      { key: 'premium', name: 'Signature', text: 'The full operating system: the owner knows everything, channels run themselves.', features: ['Everything in Professional', 'Ask your hotel: owner AI + morning report', 'Real-time sync with Booking, Airbnb, Expedia', 'AI voice assistant (100 min included)', 'Fraud alerts and price suggestions'] },
      { key: 'enterprise', name: 'Enterprise', text: 'Resorts and groups: your system, on your server.', features: ['Same code, customized', 'Own server and brand', 'Modules on request', 'Custom integrations', 'Maintenance and SLA'] },
    ],
  },
  faq: {
    eyebrow: 'FAQ',
    title: 'What owners ask.',
    items: [
      { q: 'Is my invoicing legal?', a: 'The system is built for fiscalization with certified providers (easyPos, fature.al). Each hotel has its own fiscal certificate, as with any system. We make the connection and keep it simple.' },
      { q: 'Does it connect to Booking.com and Airbnb?', a: 'Yes, with free iCal sync (bookings flow in, dates block). For real-time sync with prices and availability we offer a monthly add-on.' },
      { q: 'Does the AI read everything I say to guests?', a: 'The AI only answers what you allow and never invents prices or availability. You see every conversation and can take over any time. Passports are not stored as photos.' },
      { q: 'What happens to guest data?', a: 'Servers are in the European Union. Document data is deleted automatically after the stay and each hotel only sees its own data.' },
      { q: 'Do I need a card to pay?', a: 'No. We accept cash at first. Automatic payment comes later, if you want it.' },
      { q: 'What if there is no internet?', a: 'Offline fiscalization is on our roadmap and we will tell you when it is ready. Today the system works online.' },
    ],
  },
  cta: {
    title: 'Let’s try it with your hotel.',
    sub: 'Leave your name and a number. We contact you within the day and set your hotel up with no upfront cost.',
    name: 'Your name',
    hotel: 'Hotel',
    phone: 'Phone or WhatsApp',
    send: 'Send',
    sent: 'Thank you! We will contact you very soon.',
    error: 'Not sent. Message us directly on WhatsApp or email.',
    or: 'or write directly',
    whatsapp: 'WhatsApp',
    email: 'Email',
  },
  footer: { made: 'Built in Albania, for Albanian hotels.', demo: 'Demo', resort: 'Demo resort website', login: 'Log in' },
};

export const pickMarketingCopy = makeCopy(sq, en);
