import { makeCopy } from '@/lib/copy';

const sq = {
  book: 'Rezervo',
  bookNow: 'Rezervo tani',
  directBest: 'Rezervo direkt · pa komision · çmimi më i mirë',
  eyebrow: 'Bregdeti Jonian · Shqipëri',
  heroSub: 'Një vend ku deti të zgjon, guri të ngroh dhe koha ngadalësohet.',
  scroll: 'Zbrit',
  checkIn: 'Mbërritja',
  checkOut: 'Largimi',
  adults: 'Të rritur',
  children: 'Fëmijë',
  search: 'Shiko disponueshmërinë',
  searching: 'Po kërkoj…',
  nav: { rooms: 'Dhomat', experiences: 'Përvojat', spa: 'Spa', contact: 'Kontakti' },
  roomsTitle: 'Dhomat',
  roomsSub: 'Secila me pamjen e vet, secila me qetësinë e vet.',
  perNight: 'për natë',
  from: 'nga',
  sqm: 'm²',
  upTo: (n: number) => `deri ${n} persona`,
  choose: 'Zgjidh',
  left: (n: number) => (n === 1 ? 'Mbetet 1 dhomë' : `Mbeten ${n} dhoma`),
  unavailable: 'Nuk është e lirë për këto data',
  results: 'Dhomat e lira',
  nights: (n: number) => (n === 1 ? '1 natë' : `${n} net`),
  totalFor: 'gjithsej',
  experiencesTitle: 'Tavolina, banaku, uji',
  experiencesSub: 'Nga mëngjesi te kokteji i fundit i ditës.',
  outlet: { restaurant: 'Restorant', bar: 'Bar', pool_bar: 'Bari i pishinës', spa: 'Spa', room_service: 'Shërbim në dhomë' } as Record<string, string>,
  spaTitle: 'Spa dhe qetësi',
  spaSub: 'Trajtime që zgjasin sa një perëndim dielli.',
  minutes: 'min',
  contactTitle: 'Na shkruaj',
  contactSub: 'Pyetje, dasma, grupe apo një dëshirë e veçantë. Përgjigjemi shpejt.',
  name: 'Emri',
  email: 'Email',
  phone: 'Telefoni',
  message: 'Mesazhi',
  send: 'Dërgo mesazhin',
  sent: 'Faleminderit! Mesazhi u dërgua. Do t’ju përgjigjemi shumë shpejt.',
  yourDetails: 'Të dhënat e tua',
  first: 'Emri',
  last: 'Mbiemri',
  requests: 'Kërkesa të veçanta (opsionale)',
  payHotel: 'Paguaj në hotel',
  payHotelHint: 'Pa pagesë tani. Rezervimi konfirmohet menjëherë.',
  payDeposit: 'Paguaj paradhënien online',
  payDepositHint: 'Siguron dhomën. Pjesa tjetër paguhet në hotel.',
  confirm: 'Konfirmo rezervimin',
  confirming: 'Po konfirmohet…',
  back: 'Kthehu',
  summary: 'Përmbledhja',
  privacy: 'Të dhënat përdoren vetëm për rezervimin tuaj.',
  poweredBy: 'Sistemi i rezervimeve nga',
  errors: {
    invalid: 'Kontrollo fushat e plotësuara.', notFound: 'Ky hotel nuk u gjet.', pastDate: 'Mbërritja nuk mund të jetë në të kaluarën.',
    nights: 'Zgjidh të paktën një natë.', tooFar: 'Data është shumë larg.', busy: 'Sistemi është i zënë. Provo pas pak.',
    soldOut: 'Nuk ka dhoma të lira për këto data.', closed: 'Një nga netët nuk është e hapur për rezervim.', minStay: 'Nuk plotësohet qëndrimi minimal.',
    occupancy: 'Shumë persona për këtë dhomë.', type: 'Lloji i dhomës nuk është aktiv.', unknown: 'Diçka shkoi keq. Provo përsëri.', nothingDue: 'Nuk ka pagesë për t’u bërë.',
  } as Record<string, string>,
  confirmation: {
    title: 'Rezervimi yt',
    thanks: 'Faleminderit',
    paidBanner: 'Pagesa u pranua. Të presim!',
    code: 'Kodi',
    stay: 'Qëndrimi',
    guests: 'Persona',
    total: 'Totali',
    paid: 'Paguar',
    due: 'Për t’u paguar',
    payNow: 'Paguaj paradhënien',
    status: { tentative: 'Në pritje të pagesës', confirmed: 'Konfirmuar', checked_in: 'Brenda', checked_out: 'Përfunduar', cancelled: 'Anuluar', no_show: 'Nuk erdhi' } as Record<string, string>,
    contact: 'Kontakt',
    back: 'Kthehu te faqja',
  },
  pay: {
    title: 'Pagesa online',
    demo: 'Ky është një checkout demo. Asnjë kartë e vërtetë nuk përdoret.',
    amount: 'Për të paguar',
    pay: 'Paguaj',
    paying: 'Po paguhet…',
  },
  chat: { open: 'Pyet asistentin', title: 'Asistenti i resortit', placeholder: 'Shkruaj një pyetje…', send: 'Dërgo', human: 'Fol me një person', thinking: 'Po shkruan…', hello: 'Përshëndetje! Mund të të ndihmoj me dhomat, çmimet, rezervimet dhe çdo pyetje për qëndrimin.' },
};

const en: typeof sq = {
  book: 'Book',
  bookNow: 'Book now',
  directBest: 'Book direct · no commission · best rate',
  eyebrow: 'Ionian Coast · Albania',
  heroSub: 'A place where the sea wakes you, the stone warms you and time slows down.',
  scroll: 'Scroll',
  checkIn: 'Check-in',
  checkOut: 'Check-out',
  adults: 'Adults',
  children: 'Children',
  search: 'Check availability',
  searching: 'Searching…',
  nav: { rooms: 'Rooms', experiences: 'Experiences', spa: 'Spa', contact: 'Contact' },
  roomsTitle: 'Rooms',
  roomsSub: 'Each with its own view, each with its own calm.',
  perNight: 'per night',
  from: 'from',
  sqm: 'm²',
  upTo: (n: number) => `up to ${n} guests`,
  choose: 'Select',
  left: (n: number) => (n === 1 ? '1 room left' : `${n} rooms left`),
  unavailable: 'Not available for these dates',
  results: 'Available rooms',
  nights: (n: number) => (n === 1 ? '1 night' : `${n} nights`),
  totalFor: 'total',
  experiencesTitle: 'Table, bar, water',
  experiencesSub: 'From breakfast to the day’s last cocktail.',
  outlet: { restaurant: 'Restaurant', bar: 'Bar', pool_bar: 'Pool bar', spa: 'Spa', room_service: 'Room service' },
  spaTitle: 'Spa and stillness',
  spaSub: 'Treatments that last as long as a sunset.',
  minutes: 'min',
  contactTitle: 'Write to us',
  contactSub: 'Questions, weddings, groups or a special wish. We reply quickly.',
  name: 'Name',
  email: 'Email',
  phone: 'Phone',
  message: 'Message',
  send: 'Send message',
  sent: 'Thank you! Your message was sent. We will reply very soon.',
  yourDetails: 'Your details',
  first: 'First name',
  last: 'Last name',
  requests: 'Special requests (optional)',
  payHotel: 'Pay at the hotel',
  payHotelHint: 'Nothing to pay now. Booking is confirmed instantly.',
  payDeposit: 'Pay a deposit online',
  payDepositHint: 'Secures the room. The rest is paid at the hotel.',
  confirm: 'Confirm booking',
  confirming: 'Confirming…',
  back: 'Back',
  summary: 'Summary',
  privacy: 'Your details are used only for your booking.',
  poweredBy: 'Booking system by',
  errors: {
    invalid: 'Check the fields.', notFound: 'This hotel was not found.', pastDate: 'Arrival cannot be in the past.',
    nights: 'Pick at least one night.', tooFar: 'That date is too far ahead.', busy: 'The system is busy. Try again shortly.',
    soldOut: 'No rooms left for those dates.', closed: 'One of the nights is not open for booking.', minStay: 'Minimum stay not met.',
    occupancy: 'Too many guests for this room.', type: 'Room type is not active.', unknown: 'Something went wrong. Try again.', nothingDue: 'Nothing to pay.',
  },
  confirmation: {
    title: 'Your booking',
    thanks: 'Thank you',
    paidBanner: 'Payment received. See you soon!',
    code: 'Code',
    stay: 'Stay',
    guests: 'Guests',
    total: 'Total',
    paid: 'Paid',
    due: 'Due',
    payNow: 'Pay the deposit',
    status: { tentative: 'Awaiting payment', confirmed: 'Confirmed', checked_in: 'In house', checked_out: 'Completed', cancelled: 'Cancelled', no_show: 'No-show' },
    contact: 'Contact',
    back: 'Back to the website',
  },
  pay: {
    title: 'Online payment',
    demo: 'This is a demo checkout. No real card is used.',
    amount: 'Amount to pay',
    pay: 'Pay',
    paying: 'Paying…',
  },
  chat: { open: 'Ask the assistant', title: 'Resort assistant', placeholder: 'Type a question…', send: 'Send', human: 'Talk to a person', thinking: 'Typing…', hello: 'Hello! I can help with rooms, prices, bookings and any question about your stay.' },
};

export const pickResortCopy = makeCopy(sq, en);
export type ResortCopy = typeof sq;
