import { makeCopy } from '@/lib/copy';

const sq = {
  eyebrow: 'Spa dhe wellness',
  title: 'Qetësia ka orar.',
  subtitle: 'Terapistët, trajtimet dhe mysafirët në një ditë të vetme. Ngarkoje në dhomë kur të përfundojë.',
  today: 'Sot',
  therapist: 'Terapisti',
  service: 'Trajtimi',
  time: 'Ora',
  guest: 'Mysafiri',
  inHouse: 'Mysafir brenda',
  walkIn: 'Mysafir i jashtëm',
  guestName: 'Emri i mysafirit',
  notes: 'Shënime',
  book: 'Rezervo',
  booking: 'Rezervim i ri',
  cancel: 'Mbyll',
  min: 'min',
  services: 'Trajtimet',
  addService: 'Shto trajtim',
  nameSq: 'Emri (shqip)',
  nameEn: 'Emri (anglisht)',
  duration: 'Kohëzgjatja (min)',
  price: 'Çmimi',
  active: 'Aktiv',
  save: 'Ruaj',
  status: { booked: 'Rezervuar', confirmed: 'Konfirmuar', completed: 'Përfunduar', cancelled: 'Anuluar', no_show: 'Nuk erdhi' } as Record<string, string>,
  actions: { confirmed: 'Konfirmo', completed: 'Përfundoi', cancelled: 'Anulo', no_show: 'Nuk erdhi', charge: 'Ngarko në dhomë' },
  charged: 'E ngarkuar në dhomë',
  errors: {
    invalid: 'Kontrollo fushat.', forbidden: 'Nuk ke leje.', module: 'Moduli është i çaktivizuar.', notFound: 'Nuk u gjet.', guestRequired: 'Shkruaj emrin ose zgjidh mysafirin.',
    outsideHours: 'Jashtë orarit të spa-së (09:00–21:00).', therapistBusy: 'Terapisti është i zënë në këtë orar.', alreadyCharged: 'Është ngarkuar tashmë.',
    noBooking: 'Ky mysafir nuk është lidhur me një rezervim.', badStatus: 'Statusi nuk e lejon.', notInHouse: 'Mysafiri nuk është brenda.', unknown: 'Diçka shkoi keq.',
  } as Record<string, string>,
};

const en: typeof sq = {
  eyebrow: 'Spa and wellness',
  title: 'Stillness, on a schedule.',
  subtitle: 'Therapists, treatments and guests in a single day. Charge it to the room once it is done.',
  today: 'Today',
  therapist: 'Therapist',
  service: 'Treatment',
  time: 'Time',
  guest: 'Guest',
  inHouse: 'In-house guest',
  walkIn: 'Outside guest',
  guestName: 'Guest name',
  notes: 'Notes',
  book: 'Book',
  booking: 'New appointment',
  cancel: 'Close',
  min: 'min',
  services: 'Treatments',
  addService: 'Add treatment',
  nameSq: 'Name (Albanian)',
  nameEn: 'Name (English)',
  duration: 'Duration (min)',
  price: 'Price',
  active: 'Active',
  save: 'Save',
  status: { booked: 'Booked', confirmed: 'Confirmed', completed: 'Completed', cancelled: 'Cancelled', no_show: 'No-show' },
  actions: { confirmed: 'Confirm', completed: 'Completed', cancelled: 'Cancel', no_show: 'No-show', charge: 'Charge to room' },
  charged: 'Charged to room',
  errors: {
    invalid: 'Check the fields.', forbidden: 'Not allowed.', module: 'Module disabled.', notFound: 'Not found.', guestRequired: 'Enter a name or pick a guest.',
    outsideHours: 'Outside spa hours (09:00–21:00).', therapistBusy: 'The therapist is busy at that time.', alreadyCharged: 'Already charged.',
    noBooking: 'This guest is not linked to a booking.', badStatus: 'Status does not allow this.', notInHouse: 'The guest is not in house.', unknown: 'Something went wrong.',
  },
};

export const pickSpaCopy = makeCopy(sq, en);
