/** Human labels for audit_logs.action. Unknown actions fall back to the raw key. */
export const AUDIT_LABELS: Record<string, { sq: string; en: string }> = {
  'booking.created': { sq: 'Krijoi rezervim', en: 'Created a booking' },
  'booking.confirmed': { sq: 'Konfirmoi rezervim', en: 'Confirmed a booking' },
  'booking.moved': { sq: 'Zhvendosi rezervim në kalendar', en: 'Moved a booking on the calendar' },
  'booking.room_assigned': { sq: 'Caktoi dhomë', en: 'Assigned a room' },
  'booking.room_unassigned': { sq: 'Hoqi dhomën', en: 'Unassigned the room' },
  'booking.upgraded': { sq: 'Përmirësoi dhomën', en: 'Upgraded the room' },
  'booking.checked_in': { sq: 'Regjistroi hyrjen', en: 'Checked a guest in' },
  'booking.checked_out': { sq: 'Regjistroi daljen', en: 'Checked a guest out' },
  'booking.cancelled': { sq: 'Anuloi rezervim', en: 'Cancelled a booking' },
  'booking.no_show': { sq: 'Shënoi “nuk erdhi”', en: 'Marked a no-show' },
  'payment.recorded': { sq: 'Regjistroi pagesë', en: 'Recorded a payment' },
  'payment.refunded': { sq: 'Bëri rimbursim', en: 'Issued a refund' },
  'payment.online': { sq: 'Pagesë online', en: 'Online payment' },
  'folio.charge_posted': { sq: 'Shtoi shpenzim në faturë', en: 'Posted a folio charge' },
  'folio.charge_voided': { sq: 'Anuloi shpenzim', en: 'Voided a charge' },
  'guest.updated': { sq: 'Përditësoi mysafirin', en: 'Updated a guest' },
  'rates.updated': { sq: 'Ndryshoi çmimet', en: 'Changed rates' },
  'pos.order_paid': { sq: 'Mbylli porosi POS', en: 'Closed a POS order' },
  'pos.order_voided': { sq: 'Anuloi porosi POS', en: 'Voided a POS order' },
  'pos.discount_applied': { sq: 'Aplikoi zbritje', en: 'Applied a discount' },
  'pos.stock_adjusted': { sq: 'Ndryshoi stokun', en: 'Adjusted stock' },
  'spa.booked': { sq: 'Rezervoi spa', en: 'Booked a spa slot' },
  'spa.charged_to_room': { sq: 'Ngarkoi spa në dhomë', en: 'Charged spa to a room' },
  'spa.service_saved': { sq: 'Ruajti trajtim spa', en: 'Saved a spa treatment' },
  'invoice.issued': { sq: 'Lëshoi faturë', en: 'Issued an invoice' },
  'invoice.fiscalized': { sq: 'Fiskalizoi faturë', en: 'Fiscalized an invoice' },
  'invoice.cancelled': { sq: 'Anuloi faturë', en: 'Cancelled an invoice' },
  'cash_shift.opened': { sq: 'Hapi turnin e arkës', en: 'Opened a cash shift' },
  'cash_shift.closed': { sq: 'Mbylli turnin e arkës', en: 'Closed a cash shift' },
  'expense.created': { sq: 'Shtoi shpenzim', en: 'Added an expense' },
  'expense.updated': { sq: 'Ndryshoi shpenzim', en: 'Edited an expense' },
  'expense.deleted': { sq: 'Fshiu shpenzim', en: 'Deleted an expense' },
  'housekeeping.created': { sq: 'Krijoi detyrë pastrimi', en: 'Created a cleaning task' },
  'housekeeping.status_changed': { sq: 'Ndryshoi detyrë pastrimi', en: 'Updated a cleaning task' },
  'maintenance.created': { sq: 'Raportoi defekt', en: 'Reported a fault' },
  'maintenance.resolved': { sq: 'Zgjidhi defekt', en: 'Resolved a fault' },
  'room.status_changed': { sq: 'Ndryshoi statusin e dhomës', en: 'Changed a room status' },
  'room.out_of_order': { sq: 'Nxori dhomën jashtë shërbimit', en: 'Took a room out of order' },
  'integration.updated': { sq: 'Ndryshoi integrimin', en: 'Changed an integration' },
  'channel.mapping_saved': { sq: 'Ruajti lidhjen e kanalit', en: 'Saved a channel mapping' },
  'alert.resolved': { sq: 'Zgjidhi një alarm', en: 'Resolved an alert' },
  'conversation.take': { sq: 'Mori një bisedë', en: 'Took over a conversation' },
  'conversation.ai': { sq: 'Ia ktheu bisedën AI-së', en: 'Handed a conversation to AI' },
  'conversation.resolve': { sq: 'Zgjidhi një bisedë', en: 'Resolved a conversation' },
  'ai.staff.request': { sq: 'Pyeti asistentin', en: 'Asked the assistant' },
};

export const auditLabel = (action: string, locale: string) => AUDIT_LABELS[action]?.[locale === 'en' ? 'en' : 'sq'] ?? action;
