import { makeCopy } from '@/lib/copy';

const sq = {
  eyebrow: 'Kutia e përbashkët',
  title: 'Çdo mesazh, një vend.',
  subtitle: 'WhatsApp, Instagram, Messenger dhe chat-i i faqes. AI përgjigjet vetë, ti ndërhyn kur do.',
  filters: { all: 'Aktive', needs_human: 'Të duhesh ti', ai_handling: 'AI po merret', human_handling: 'Po merresh ti', resolved: 'Të zgjidhura' },
  status: { ai_handling: 'AI po merret', needs_human: 'Të duhesh ti', human_handling: 'Po merresh ti', resolved: 'E zgjidhur' },
  channel: { whatsapp: 'WhatsApp', instagram: 'Instagram', messenger: 'Messenger', web_chat: 'Chat i faqes', email: 'Email', sms: 'SMS', voice: 'Telefon', booking_com: 'Booking.com', airbnb: 'Airbnb' } as Record<string, string>,
  empty: 'Asnjë bisedë këtu.',
  pick: 'Zgjidh një bisedë',
  pickSub: 'Mesazhet e mysafirëve shfaqen këtu në kohë reale.',
  placeholder: 'Shkruaj një përgjigje…',
  send: 'Dërgo',
  suggest: 'Sugjero me AI',
  suggesting: 'Po mendon…',
  templates: 'Përgjigje të gatshme',
  take: 'Merre ti',
  giveAi: 'Ktheja AI-së',
  resolve: 'Zgjidhe',
  aiNote: 'AI po përgjigjet automatikisht. Merre kur do ndërhyrë.',
  humanNote: (n: string | null) => `Po merret nga ${n ?? 'stafi'}. AI është i pezulluar.`,
  guest: 'Mysafiri',
  booking: 'Rezervimi',
  openBooking: 'Hap rezervimin',
  stays: (n: number) => (n === 0 ? 'Mysafir i ri' : `${n} qëndrime`),
  live: 'Drejtpërdrejt',
  photo: 'Foto e dërguar',
  aiTag: 'AI',
  errors: { forbidden: 'Nuk ke leje.', module: 'Moduli është i çaktivizuar.', notFound: 'Biseda nuk u gjet.', sendFailed: 'Mesazhi nuk u dërgua te kanali.', aiOff: 'AI nuk është konfiguruar (OPENROUTER_API_KEY).', aiLimit: 'Kufiri orar i AI u arrit.', unknown: 'Diçka shkoi keq.', invalid: 'Kontrollo fushat.' } as Record<string, string>,
};

const en: typeof sq = {
  eyebrow: 'Unified inbox',
  title: 'Every message, one place.',
  subtitle: 'WhatsApp, Instagram, Messenger and the website chat. The AI replies by itself, you step in whenever you like.',
  filters: { all: 'Active', needs_human: 'Needs you', ai_handling: 'AI handling', human_handling: 'You handling', resolved: 'Resolved' },
  status: { ai_handling: 'AI handling', needs_human: 'Needs you', human_handling: 'You handling', resolved: 'Resolved' },
  channel: { whatsapp: 'WhatsApp', instagram: 'Instagram', messenger: 'Messenger', web_chat: 'Website chat', email: 'Email', sms: 'SMS', voice: 'Phone', booking_com: 'Booking.com', airbnb: 'Airbnb' },
  empty: 'No conversations here.',
  pick: 'Pick a conversation',
  pickSub: 'Guest messages show up here in real time.',
  placeholder: 'Write a reply…',
  send: 'Send',
  suggest: 'Suggest with AI',
  suggesting: 'Thinking…',
  templates: 'Quick replies',
  take: 'Take over',
  giveAi: 'Hand back to AI',
  resolve: 'Resolve',
  aiNote: 'The AI is replying automatically. Take over whenever you want.',
  humanNote: (n) => `Handled by ${n ?? 'staff'}. The AI is paused.`,
  guest: 'Guest',
  booking: 'Booking',
  openBooking: 'Open booking',
  stays: (n) => (n === 0 ? 'New guest' : `${n} stays`),
  live: 'Live',
  photo: 'Photo sent',
  aiTag: 'AI',
  errors: { forbidden: 'Not allowed.', module: 'Module disabled.', notFound: 'Conversation not found.', sendFailed: 'The message could not be delivered to the channel.', aiOff: 'AI is not configured (OPENROUTER_API_KEY).', aiLimit: 'Hourly AI limit reached.', unknown: 'Something went wrong.', invalid: 'Check the fields.' },
};

export const pickInboxCopy = makeCopy(sq, en);
