import { makeCopy } from '@/lib/copy';

const sq = {
  eyebrow: 'Menaxheri i kanaleve',
  title: 'Një kalendar. Të gjitha kanalet.',
  subtitle: 'Lidh Booking.com, Airbnb dhe Expedia. Rezervimet hyjnë vetë, datat bllokohen kudo dhe mbi-rezervimet të bien në sy para se të ndodhin.',
  syncAll: 'Sinkronizo tani',
  push: 'Dërgo disponueshmërinë',
  sections: {
    feeds: 'Lidhja me kanalet (iCal)',
    feedsHint: 'Ngjit lidhjen iCal që të jep kanali për secilin lloj dhome. Sinkronizimi krijon, ndryshon dhe anulon rezervimet automatikisht.',
    exports: 'Dërgo kalendarin tënd te kanalet',
    exportsHint: 'Një lidhje e nënshkruar për çdo dhomë. Ngjite te “Import calendar” në Booking.com, Airbnb ose Expedia. Nuk përmban të dhëna mysafirësh.',
    integrations: 'Shërbimet e lidhura',
    integrationsHint: 'Çdo shërbim punon në një nga tre mënyrat: provë (pa rrjet), sandbox (test) ose live (real).',
    log: 'Historiku i sinkronizimit',
  },
  channel: { booking_com: 'Booking.com', airbnb: 'Airbnb', expedia: 'Expedia', agoda: 'Agoda' } as Record<string, string>,
  feedUrl: 'Lidhja iCal e importit (https)',
  extRoom: 'ID e dhomës te Channex',
  extRate: 'ID e planit të çmimit',
  save: 'Ruaj',
  saved: 'U ruajt.',
  sync: 'Sinkronizo',
  lastSync: 'Sinkronizimi i fundit',
  never: 'Asnjëherë',
  copy: 'Kopjo',
  copied: 'U kopjua',
  syncResult: (r: { created: number; updated: number; cancelled: number; conflicts: number }) =>
    `Të reja: ${r.created} · të ndryshuara: ${r.updated} · të anuluara: ${r.cancelled}${r.conflicts ? ` · konflikte: ${r.conflicts}` : ''}`,
  pushResult: (r: { mode: string; rows: number; pushed: boolean }) => (r.pushed ? `U dërguan ${r.rows} ditë-dhoma te Channex (${r.mode}).` : `Provë: ${r.rows} ditë-dhoma janë llogaritur, asgjë nuk u dërgua.`),
  mode: { mock: 'Provë', sandbox: 'Sandbox', live: 'Live' },
  enabled: 'Aktiv',
  needsKey: 'Mungon çelësi në mjedis',
  providerName: {
    channex: 'Channex (kanalet OTA)',
    ical: 'Sinkronizimi iCal',
    meta_whatsapp: 'WhatsApp Business',
    meta_instagram: 'Instagram',
    meta_messenger: 'Messenger',
    paysera: 'Paysera (pagesa online)',
    easypos: 'easyPos (fiskalizim)',
    fature_al: 'fature.al (fiskalizim)',
    vapi: 'Vapi (asistenti zanor)',
    resend: 'Resend (email)',
    ai: 'AI (OpenRouter)',
    telegram: 'Telegram',
  } as Record<string, string>,
  logAction: { 'channel.sync': 'Sinkronizim', 'channel.sync_failed': 'Sinkronizim i dështuar', 'channel.push': 'Dërgim disponueshmërie', 'channel.mapping_saved': 'Lidhje e ruajtur' } as Record<string, string>,
  errors: {
    invalid: 'Kontrollo fushat.', forbidden: 'Kjo kërkon leje menaxheri.', module: 'Moduli është i çaktivizuar.', unknown: 'Diçka shkoi keq.',
    envMissing: 'Shto çelësat në variablat e mjedisit fillimisht.', demoLive: 'Demo nuk lejohet të kalojë në live.',
    badUrl: 'Lidhja duhet të jetë https publike.', noFeed: 'Kjo lidhje nuk ka URL iCal.', syncFailed: 'Sinkronizimi dështoi. Kontrollo lidhjen.',
    notMapped: 'Plotëso ID-të e Channex dhe ID-në e pronës fillimisht.', pushFailed: 'Dërgimi te Channex dështoi.', type: 'Lloji i dhomës nuk u gjet.',
  } as Record<string, string>,
};

const en: typeof sq = {
  eyebrow: 'Channel manager',
  title: 'One calendar. Every channel.',
  subtitle: 'Connect Booking.com, Airbnb and Expedia. Reservations flow in by themselves, dates block everywhere, and overbookings show up before they happen.',
  syncAll: 'Sync now',
  push: 'Push availability',
  sections: {
    feeds: 'Channel connections (iCal)',
    feedsHint: 'Paste the iCal link each channel gives you per room type. Syncing creates, changes and cancels bookings automatically.',
    exports: 'Send your calendar to the channels',
    exportsHint: 'One signed link per room. Paste it into “Import calendar” on Booking.com, Airbnb or Expedia. It contains no guest data.',
    integrations: 'Connected services',
    integrationsHint: 'Every service runs in one of three modes: mock (no network), sandbox (test) or live (real).',
    log: 'Sync history',
  },
  channel: { booking_com: 'Booking.com', airbnb: 'Airbnb', expedia: 'Expedia', agoda: 'Agoda' },
  feedUrl: 'Import iCal link (https)',
  extRoom: 'Channex room ID',
  extRate: 'Rate plan ID',
  save: 'Save',
  saved: 'Saved.',
  sync: 'Sync',
  lastSync: 'Last sync',
  never: 'Never',
  copy: 'Copy',
  copied: 'Copied',
  syncResult: (r) => `New: ${r.created} · changed: ${r.updated} · cancelled: ${r.cancelled}${r.conflicts ? ` · conflicts: ${r.conflicts}` : ''}`,
  pushResult: (r) => (r.pushed ? `${r.rows} room-days sent to Channex (${r.mode}).` : `Mock: ${r.rows} room-days computed, nothing sent.`),
  mode: { mock: 'Mock', sandbox: 'Sandbox', live: 'Live' },
  enabled: 'Enabled',
  needsKey: 'Key missing in environment',
  providerName: {
    channex: 'Channex (OTA channels)',
    ical: 'iCal sync',
    meta_whatsapp: 'WhatsApp Business',
    meta_instagram: 'Instagram',
    meta_messenger: 'Messenger',
    paysera: 'Paysera (online payments)',
    easypos: 'easyPos (fiscalization)',
    fature_al: 'fature.al (fiscalization)',
    vapi: 'Vapi (voice assistant)',
    resend: 'Resend (email)',
    ai: 'AI (OpenRouter)',
    telegram: 'Telegram',
  },
  logAction: { 'channel.sync': 'Sync', 'channel.sync_failed': 'Sync failed', 'channel.push': 'Availability push', 'channel.mapping_saved': 'Mapping saved' },
  errors: {
    invalid: 'Check the fields.', forbidden: 'This needs manager permission.', module: 'This module is disabled.', unknown: 'Something went wrong.',
    envMissing: 'Add the keys to the environment variables first.', demoLive: 'The demo cannot go live.',
    badUrl: 'The link must be a public https URL.', noFeed: 'This mapping has no iCal URL.', syncFailed: 'Sync failed. Check the link.',
    notMapped: 'Fill in the Channex IDs and property ID first.', pushFailed: 'Push to Channex failed.', type: 'Room type not found.',
  },
};

export const pickChannelsCopy = makeCopy(sq, en);
