import { makeCopy } from '@/lib/copy';

const sq = {
  eyebrow: 'Kalendari kryesor',
  title: 'Gjithë hoteli, natë pas nate.',
  subtitle: 'Merr një rezervim dhe vendose në një dhomë tjetër. Zgjate një qëndrim duke tërhequr skajin. Çmimet dhe disponueshmëria ndryshojnë aty për aty.',
  today: 'Sot',
  prev: 'Para',
  next: 'Pas',
  span: (n: number) => `${n} ditë`,
  rooms: 'Dhomat',
  room: 'Dhoma',
  free: 'të lira',
  live: 'Drejtpërdrejt',
  unassigned: 'Pa dhomë',
  dropHere: 'Lëshoje këtu për ta hequr nga dhoma',
  legend: 'Burimet',
  weekdays: ['Die', 'Hën', 'Mar', 'Mër', 'Enj', 'Pre', 'Sht'],
  nights: (n: number) => (n === 1 ? '1 natë' : `${n} net`),
  status: { tentative: 'Në pritje', confirmed: 'Konfirmuar', checked_in: 'Brenda', checked_out: 'Larguar' } as Record<string, string>,
  source: { direct: 'Direkt', website: 'Faqja', booking_com: 'Booking.com', airbnb: 'Airbnb', expedia: 'Expedia', agoda: 'Agoda', whatsapp: 'WhatsApp', instagram: 'Instagram', messenger: 'Messenger', phone: 'Telefon', ai_voice: 'Asistenti zanor', walk_in: 'Pa rezervim' } as Record<string, string>,
  moved: 'Rezervimi u zhvendos.',
  detail: { open: 'Hap rezervimin', code: 'Kodi', stay: 'Qëndrimi', guests: 'Persona', total: 'Totali', paid: 'Paguar', source: 'Burimi' },
  quick: {
    title: 'Rezervim i shpejtë',
    room: 'Dhoma',
    checkIn: 'Mbërritja',
    nights: 'Net',
    adults: 'Të rritur',
    firstName: 'Emri',
    lastName: 'Mbiemri',
    phone: 'Telefoni',
    source: 'Burimi',
    status: 'Statusi',
    create: 'Krijo rezervimin',
    creating: 'Po krijohet…',
    cancel: 'Anulo',
  },
  rates: {
    title: 'Çmimet dhe disponueshmëria',
    type: 'Lloji i dhomës',
    from: 'Nga',
    to: 'Deri',
    price: 'Çmimi për natë',
    pct: 'ose ndrysho me %',
    minStay: 'Qëndrim minimal',
    closed: 'Mbyllur për shitje',
    open: 'Hapur për shitje',
    keep: 'Pa ndryshim',
    days: 'Ditët e javës',
    all: 'Të gjitha',
    save: 'Ruaj çmimet',
    saved: (n: number) => `U përditësuan ${n} ditë.`,
    hint: 'Lëri bosh çfarë nuk do ta ndryshosh.',
    edit: 'Ndrysho çmimet',
    closedDay: 'Mbyllur',
    minStayShort: 'min.',
  },
  errors: {
    invalid: 'Kontrollo fushat.',
    forbidden: 'Nuk ke leje për këtë veprim.',
    module: 'Moduli është i çaktivizuar.',
    unknown: 'Diçka shkoi keq. Provo përsëri.',
    notFound: 'Rezervimi nuk u gjet.',
    badStatus: 'Ky rezervim nuk mund të lëvizet në këtë status.',
    pastDate: 'Mbërritja nuk mund të jetë në të kaluarën.',
    stayOver: 'Data e largimit duhet të jetë pas sotit.',
    nights: 'Qëndrimi duhet të ketë të paktën 1 natë.',
    roomInvalid: 'Dhoma nuk është e disponueshme.',
    roomNotReady: 'Dhoma nuk është e pastër ende.',
    roomTaken: 'Dhoma është e zënë për këto data.',
    soldOut: 'Nuk ka dhoma të lira për këto data.',
    closed: 'Një nga netët është e mbyllur për shitje.',
    minStay: 'Nuk plotësohet qëndrimi minimal.',
    occupancy: 'Shumë persona për këtë dhomë.',
    type: 'Lloji i dhomës nuk është aktiv.',
    guestRequired: 'Shto emrin e mysafirit.',
    email: 'Email i pavlefshëm.',
    duplicate: 'Ekziston tashmë.',
  } as Record<string, string>,
};

const en: typeof sq = {
  eyebrow: 'Master calendar',
  title: 'The whole hotel, night by night.',
  subtitle: 'Grab a booking and drop it in another room. Stretch a stay by dragging its edge. Prices and availability change right here.',
  today: 'Today',
  prev: 'Back',
  next: 'Next',
  span: (n: number) => `${n} days`,
  rooms: 'Rooms',
  room: 'Room',
  free: 'free',
  live: 'Live',
  unassigned: 'Unassigned',
  dropHere: 'Drop here to remove from the room',
  legend: 'Sources',
  weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  nights: (n: number) => (n === 1 ? '1 night' : `${n} nights`),
  status: { tentative: 'Tentative', confirmed: 'Confirmed', checked_in: 'In house', checked_out: 'Checked out' },
  source: { direct: 'Direct', website: 'Website', booking_com: 'Booking.com', airbnb: 'Airbnb', expedia: 'Expedia', agoda: 'Agoda', whatsapp: 'WhatsApp', instagram: 'Instagram', messenger: 'Messenger', phone: 'Phone', ai_voice: 'AI voice', walk_in: 'Walk-in' },
  moved: 'Booking moved.',
  detail: { open: 'Open booking', code: 'Code', stay: 'Stay', guests: 'Guests', total: 'Total', paid: 'Paid', source: 'Source' },
  quick: {
    title: 'Quick booking',
    room: 'Room',
    checkIn: 'Check-in',
    nights: 'Nights',
    adults: 'Adults',
    firstName: 'First name',
    lastName: 'Last name',
    phone: 'Phone',
    source: 'Source',
    status: 'Status',
    create: 'Create booking',
    creating: 'Creating…',
    cancel: 'Cancel',
  },
  rates: {
    title: 'Rates and availability',
    type: 'Room type',
    from: 'From',
    to: 'To',
    price: 'Price per night',
    pct: 'or change by %',
    minStay: 'Minimum stay',
    closed: 'Closed for sale',
    open: 'Open for sale',
    keep: 'No change',
    days: 'Weekdays',
    all: 'All',
    save: 'Save rates',
    saved: (n: number) => `${n} days updated.`,
    hint: 'Leave blank whatever you do not want to change.',
    edit: 'Edit rates',
    closedDay: 'Closed',
    minStayShort: 'min.',
  },
  errors: {
    invalid: 'Check the fields.',
    forbidden: 'You are not allowed to do this.',
    module: 'This module is disabled.',
    unknown: 'Something went wrong. Try again.',
    notFound: 'Booking not found.',
    badStatus: 'This booking cannot be moved in its current status.',
    pastDate: 'Arrival cannot be in the past.',
    stayOver: 'Departure must be after today.',
    nights: 'A stay needs at least 1 night.',
    roomInvalid: 'That room is not available.',
    roomNotReady: 'The room is not clean yet.',
    roomTaken: 'The room is taken for those dates.',
    soldOut: 'No rooms left for those dates.',
    closed: 'One of the nights is closed for sale.',
    minStay: 'Minimum stay not met.',
    occupancy: 'Too many guests for this room.',
    type: 'Room type is not active.',
    guestRequired: 'Add the guest name.',
    email: 'Invalid email.',
    duplicate: 'Already exists.',
  },
};

export const pickCalendarCopy = makeCopy(sq, en);
export type CalendarCopy = typeof sq;
