const sq = {
  eyebrow: 'Kalendari · në kohë reale',
  title: 'Gjithë hoteli, në një shikim.',
  hint: 'Tërhiq rezervimin për ta zhvendosur · tërhiq skajin e djathtë për ta zgjatur · kliko për detajet',
  today: 'Sot',
  prev: 'Mbrapa',
  next: 'Përpara',
  window: (n: number) => `${n} ditë`,
  zoomIn: 'Zmadho',
  zoomOut: 'Zvogëlo',
  rates: 'Çmimet',
  live: 'Live',
  offline: 'Jo live',
  unassigned: 'Pa dhomë',
  rooms: (n: number) => (n === 1 ? '1 dhomë' : `${n} dhoma`),
  left: 'të lira',
  closed: 'Mbyllur për shitje',
  minStay: (n: number) => `Min. ${n} net`,
  noRooms: 'Nuk ka ende dhoma aktive.',
  moved: (room: string) => `U zhvendos në dhomën ${room}.`,
  unassignedOk: 'Rezervimi mbeti pa dhomë.',
  saved: 'Qëndrimi u përditësua.',
  ratesSaved: (n: number) => `U përditësuan ${n} ditë.`,
  roomStatus: { clean: 'E pastër', inspected: 'E kontrolluar', dirty: 'Për pastrim', out_of_order: 'Jashtë shërbimit' },
  change: {
    title: 'Ndrysho qëndrimin',
    before: 'Tani',
    after: 'Pas ndryshimit',
    price: 'Çmimi i qëndrimit',
    keep: 'Mbaj çmimin',
    requote: 'Rillogarit',
    checking: 'Po kontrolloj disponueshmërinë…',
    confirm: 'Ruaj ndryshimin',
    cancel: 'Anulo',
    upgrade: 'Përmirësim dhome',
    requoteNote: 'Kur ndryshon numri i netëve, çmimi rillogaritet. Vetëm menaxheri mund ta mbajë të vjetrin.',
    ota: 'Rezervim nga OTA: çmimi zakonisht vjen nga kanali. Kontrolloje para se ta rillogarisësh.',
    warnings: {
      closed: 'Përfshin net të mbyllura për shitje (lejohet për stafin).',
      minStay: 'Më pak se qëndrimi minimal (lejohet për stafin).',
    },
  },
  ratesForm: {
    title: 'Çmimet dhe shitja',
    subtitle: 'Ndrysho çmimin, qëndrimin minimal ose mbyll shitjen për një periudhë.',
    type: 'Lloji i dhomës',
    from: 'Nga',
    to: 'Deri (përfshirë)',
    weekdays: 'Ditët e javës',
    price: 'Çmimi për natë',
    minStay: 'Qëndrimi minimal (net)',
    sale: 'Shitja',
    unchanged: 'Pa ndryshim',
    open: 'E hapur',
    closed: 'E mbyllur',
    blank: 'Fushat bosh mbeten siç janë.',
    current: 'Tani',
    save: 'Ruaj',
  },
  errors: {
    inHouseDates: 'Mysafiri është brenda: mund të ndryshosh vetëm datën e largimit.',
    inHouseRoom: 'Për mysafirët brenda, zhvendos dhomën pa ndryshuar datat.',
    range: 'Periudha maksimale është 1 vit.',
    nothing: 'Zgjidh të paktën një ndryshim.',
  } as Record<string, string>,
};

const en: typeof sq = {
  eyebrow: 'Calendar · live',
  title: 'The whole hotel, at a glance.',
  hint: 'Drag a booking to move it · drag its right edge to extend · click for details',
  today: 'Today',
  prev: 'Back',
  next: 'Forward',
  window: (n) => `${n} days`,
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  rates: 'Rates',
  live: 'Live',
  offline: 'Offline',
  unassigned: 'Unassigned',
  rooms: (n) => (n === 1 ? '1 room' : `${n} rooms`),
  left: 'left',
  closed: 'Closed for sale',
  minStay: (n) => `Min. ${n} nights`,
  noRooms: 'No active rooms yet.',
  moved: (room) => `Moved to room ${room}.`,
  unassignedOk: 'Booking left unassigned.',
  saved: 'Stay updated.',
  ratesSaved: (n) => `Updated ${n} days.`,
  roomStatus: { clean: 'Clean', inspected: 'Inspected', dirty: 'Needs cleaning', out_of_order: 'Out of order' },
  change: {
    title: 'Change stay',
    before: 'Now',
    after: 'After change',
    price: 'Stay price',
    keep: 'Keep price',
    requote: 'Recalculate',
    checking: 'Checking availability…',
    confirm: 'Save change',
    cancel: 'Cancel',
    upgrade: 'Room upgrade',
    requoteNote: 'When the number of nights changes, the price is recalculated. Only a manager can keep the old one.',
    ota: 'OTA booking: the price usually comes from the channel. Check before recalculating.',
    warnings: {
      closed: 'Includes nights closed for sale (allowed for staff).',
      minStay: 'Below minimum stay (allowed for staff).',
    },
  },
  ratesForm: {
    title: 'Rates & availability',
    subtitle: 'Change price, minimum stay or close sales for a period.',
    type: 'Room type',
    from: 'From',
    to: 'To (inclusive)',
    weekdays: 'Weekdays',
    price: 'Price per night',
    minStay: 'Minimum stay (nights)',
    sale: 'Sales',
    unchanged: 'Unchanged',
    open: 'Open',
    closed: 'Closed',
    blank: 'Empty fields stay as they are.',
    current: 'Now',
    save: 'Save',
  },
  errors: {
    inHouseDates: 'Guest is in house: only the departure date can change.',
    inHouseRoom: 'For in-house guests, move the room without changing dates.',
    range: 'Maximum period is 1 year.',
    nothing: 'Choose at least one change.',
  },
};

export const calendarCopy = { sq, en };
export type CalendarCopy = typeof sq;
export const pickCalendarCopy = (locale: string) => (locale === 'en' ? en : sq);
